### ISSUE TITLE
New-TssSession failed to create session on 0.32.0-beta [Bug] 

### ISSUE THREAD

**Issue by harrychandrapdx** [thycotic-ps/thycotic.secretserver#109]
**Describe the bug**
After updating to the 0.32.0-beta module, New-TssSession failed with the following error:
![image](https://user-images.githubusercontent.com/24290978/110164822-c4849b00-7da6-11eb-98ff-20c45982bf22.png)

**To Reproduce**
1. PowerShell script:
$ssUrl = "https://xxxxxxxxxxxxxxxxxxx/SecretServer" 
$creds = New-Object System.Management.Automation.PSCredential ($ssUser, $SecurePass)
New-TssSession -SecretServer $ssUrl -Credential $creds -Verbose

1. Error/issue observed:

```
PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException:
                        404 - File or directory not found.

                        Server Error

                          404 - File or directory not found.
                          The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
TargetObject          :

                        404 - File or directory not found.
                        Server Error
                          404 - File or directory not found.
                          The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

CategoryInfo          : OperationStopped: (

                        404 - F...ble.

                        :String) [], RuntimeException
FullyQualifiedErrorId :
                        404 - File or directory not found.
                        Server Error
                          404 - File or directory not found.
                          The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-Session<Process>, C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.33.0\functions\New-Session.ps1: line 138
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PSMessageDetails      :
Exception             : System.Net.WebException: The remote server returned an error: (404) Not Found.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          :
                        404 - File or directory not found.
                        Server Error
                          404 - File or directory not found.
                          The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Invoke-RestApi<Process>, C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.33.0\functions\Invoke-RestApi.ps1: line 135
                        at New-Session<Process>, C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.33.0\functions\New-Session.ps1: line 133
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

1. Verbose output
VERBOSE: Provided command parameters: New-TssSession -SecretServer: -Credential:CredentialObject -Verbose:$True
VERBOSE: SecretServer host: https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SecretServer
VERBOSE: Performing the operation "Requesting OAuth2 token from https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SecretServer with URI of [https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SecretServeroauth2/token]" on target "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SecretServer".
VERBOSE: POST  with:    System.Collections.Specialized.OrderedDictionary

VERBOSE: POST https://xxxxxxxxxxxxxxxxxxxxxx/SecretServeroauth2/token with -1-byte payload
WARNING: Issue authenticating to [https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/SecretServer]
404 - File or directory not found.
Server Error

**Expected behavior**
The connection created successfully 

**Environment (please complete the following information):**

***Secret Server***
Build/Version: 10.9.000002

***PowerShell version***

**Name                           Value
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1**

***Host information:***

[ ] Powershell.exe
[ ] pwsh.exe
[ ] PowerShell ISE
[x ] VS Code (Stable)

VS Code, please provide the output of the following:

### VSCode extensions:
eamodio.gitlens@11.3.0
ms-azuretools.vscode-azureresourcegroups@0.3.0
ms-azuretools.vscode-azurestorage@0.12.0
ms-mssql.mssql@1.10.1
ms-vscode.azure-account@0.9.6
ms-vscode.azurecli@0.5.0
ms-vscode.powershell@2021.2.2
ms-vsts.team@1.161.1

### PowerShell version:

Name                           Value
PSVersion                      5.1.17763.1490
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1490
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional context**

**Comment by wsmelton** [comment]
A release is being pushed now that should resolve this issue: 0.33.1

**Comment by harrychandrapdx** [comment]
Thanks!! Appreciate the help!
