### ISSUE TITLE
Find-TssSecret returns partial Secret Name if "-" part of the secret name [Bug] 

### ISSUE THREAD

**Issue by harrychandrapdx** [thycotic-ps/thycotic.secretserver#111]
**Describe the bug**
Find-TssSecret returned partial secret name when the name contains "-" as part of its name.  

**To Reproduce**
1. PowerShell script: 

Find-TssSecret -FolderId "xxx" -TssSession $sess 

2. Error/issue observed:

SecretId SecretName
-------- ----------
    1686 XXX\svc_eba
    1666 XXX\svc_exxxxxxxxxxx
    1690 XXX\svc_ies
    1750 XXX\svc_ies
    1682 XXX\svc_pxxxxxxxx
    1681 XXX\svc_pexxxxxxxxxx
    1680 XXX\svc_pexxxxxxxxx
    1688 XXX\svc_sql
    3782 XXX\svc_sql
    1749 XXX\svc_sql
    1687 XXX\svc_tnrxxxxxx

1. Verbose output

```powershell
PS> Find-TssSecret -FolderId "384" -TssSession $Sess -Verbose
VERBOSE: Provided command parameters: Find-TssSecret -FolderId:384 -TssSession:TssSessionObject -Verbose:$True
VERBOSE: Provided command parameters: Get-TssVersion -TssSession:TssSessionObject
VERBOSE: GET https://xxxxxxxxxxxxxxxxxxxx.com/SecretServer/api/v1/version with 0-byte payload
VERBOSE: received 190-byte response of content type application/json; charset=utf-8
VERBOSE: Filters: filter.FolderId=384
VERBOSE: GET https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/SecretServer/api/v1/secrets/lookup?take=2147483647&filter.includeRestricted=true&filter.FolderId=384
VERBOSE: GET https://xxxxxxxxxxxxxxxxxxxxxxxxxxxx.com/SecretServer/api/v1/secrets/lookup?take=2147483647&filter.includeRestricted=true&filter.FolderId=384 with 0-byte payload
VERBOSE: received 1929-byte response of content type application/json; charset=utf-8

SecretId SecretName
-------- ----------
    1686 XXX\svc_eba
    1666 XXX\svc_exxxxxxxxxxx
    1690 XXX\svc_ies
    1750 XXX\svc_ies
    1682 XXX\svc_pxxxxxxxx
    1681 XXX\svc_pexxxxxxxxxx
    1680 XXX\svc_pexxxxxxxxx
    1688 XXX\svc_sql
    3782 XXX\svc_sql
    1749 XXX\svc_sql
    1687 XXX\svc_tnrxxxxxx
```

**Expected behavior**
The result should show the following:
SecretId SecretName
-------- ----------
    1686 XXX\svc_eba-xxx-xxx
    1666 XXX\svc_exxxxxxxxxx
    1690 XXX\svc_ies-xxx-xxx
    1750 XXX\svc_ies-xxxx-xx
    1682 XXX\svc_pxxxxxxxx
    1681 XXX\svc_pebxxxxxxxx
    1680 XXX\svc_pexxxxxxxx
    1688 XXX\svc_sql-xxx-xxx
    3782 XXX\svc_sql-xxx-xxx
    1749 XXX\svc_sql-xxx-xxx
    1687 XXX\svc_tnrxxxxxxx

**Environment (please complete the following information):**

***Secret Server***
Build/Version: 10.9.000002

***PowerShell version***

```powershell
Name Value
PSVersion 5.1.17763.1490
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17763.1490
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
```

***Host information:***

[ ] Powershell.exe
[ ] pwsh.exe
[ ] PowerShell ISE
[X] VS Code (Stable)

VS Code, please provide the output of the following:

VSCode version: 1.54.1 f30a9b73e8ffc278e71575118b6bf568f04587c8 x64
VSCode extensions:
eamodio.gitlens@11.3.0
ms-azuretools.vscode-azureresourcegroups@0.3.0
ms-azuretools.vscode-azurestorage@0.12.0
ms-mssql.mssql@1.10.1
ms-vscode.azure-account@0.9.6
ms-vscode.azurecli@0.5.0
ms-vscode.powershell@2021.2.2
ms-vsts.team@1.161.1

PSES version: 2.3.0.0
PowerShell version:
Name Value
PSVersion 5.1.17763.1490
PSEdition Desktop
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0...}
BuildVersion 10.0.17763.1490
CLRVersion 4.0.30319.42000
WSManStackVersion 3.0
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1

**Additional context**
Issue observed on 0.33.1-beta, 0.25.0-beta.

**Comment by wsmelton** [comment]
@harrychandrapdx if you want to pull the code change in 4f9d2c7 from testing this seems to fix that issue.

**Comment by harrychandrapdx** [comment]
Will do. Thank you Sir!
