### ISSUE TITLE
[Bug] Search-TssSecretTemplate not happy, unknown error

### ISSUE THREAD

**Issue by TryTryAgain** [thycotic-ps/thycotic.secretserver#161]
**Describe the bug**
`Search-TssSecretTemplate -TssSession $session -SearchText Key` fails with error:

```
WARNING: Issue on search request
Write-Error: /Users/$USER/.local/share/powershell/Modules/Thycotic.SecretServer/0.37.0/functions/secret-templates/Search-SecretTemplate.ps1:86:17
Line |
  86 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 400 (Bad Request). | @{errorCode=API_AccessDenied; message=Access Denied}

WARNING: No Secret Templates found
```

**To Reproduce**
1. PowerShell script:

```powershell
# Import the Thycotic.SecretServer module
Import-Module Thycotic.SecretServer

# Authentication and credential building
$username = "$VAULT_DOMAIN\$VAULT_USER"
$password = ConvertTo-SecureString -String "$VAULT_SECRET" -AsPlainText -Force
$cred = [pscredential]::new($username,$password)
# Store the new Thycotic PowerShell Session
$session = New-TssSession -SecretServer https://$VAULT_URL -Credential $cred

# List Secret Template types
Write-Host "Listing Secret Template types..."
Search-TssSecretTemplate -TssSession $session -SearchText Key
```

1. Error/issue observed:

```powershell
WARNING: Issue on search request
Write-Error: /Users/$USER/.local/share/powershell/Modules/Thycotic.SecretServer/0.37.0/functions/secret-templates/Search-SecretTemplate.ps1:86:17
Line |
  86 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | Response status code does not indicate success: 400 (Bad Request). | @{errorCode=API_AccessDenied; message=Access Denied}

WARNING: No Secret Templates found
```

1. Verbose output

Same as above.

**Expected behavior**
I would expect a list of templates back.

**Environment (please complete the following information):**

***Secret Server***
MacOS and CentOS7

***PowerShell version***

```powershell
7.1.3
```

***Host information:***

[ ] Powershell.exe
[x] pwsh.exe
[ ] PowerShell ISE
[ ] VS Code (Insiders/Stable)

**Additional context**
I see this feature was just added. I am able to use other thycotic-ps commands so I know auth is working.

**Comment by wsmelton** [comment]
Do you have permission in Secret Server to access Secret Templates?

**Comment by wsmelton** [comment]
> Secret Server
> MacOS and CentOS7

What version of Secret Server are you own? MacOS and CentOS7 are not valid versions of Secret Server :wink:

The output of the error indicates you do not have permission to query the endpoint used in the command `GET /secret-templates`. 

> Response status code does not indicate success: 400 (Bad Request). | @{errorCode=API_AccessDenied; message=Access Denied}

This endpoint, I believe, at a minimum requires you to have administrator rights to the templates. `Administrator role will have this permission OOB, there should be a view and then an administrator role-specific to Secret Templates. The roles are all documented [here](https://docs.thycotic.com/ss/10.9.0/roles/role-permission-list/index.md).

If you believe there is something else is ary, please provide more details indicating why it does not pertain to permissions.

**Comment by TryTryAgain** [comment]
You are correct. Those permissions must have been stripped away. Worked when I was using soap/suds with Python and an older WebServices API. Sorry about that, thanks for pointing that out. And yes, we are running Secret Server Version: 10.9.5 (not sure why/how I read that as Server OS you're running thycotic.secretserver from :P ).
