### ISSUE TITLE
[Bug] Incorrect hash for Thycotic.SecretServer.zip?

### ISSUE THREAD

**Issue by ztrhgf** [thycotic-ps/thycotic.secretserver#190]
**Describe the bug**
Hi,
I've just downloaded Thycotic.SecretServer.zip as stated here https://thycotic-ps.github.io/thycotic.secretserver/docs/install/ and check the SHA256 hash, but the result is different hash (625846DC9297963112BC2EE715BD35DF05055835FD1655DE01F3FDC08612CAAB instead of 6B33CD7D745971E6DEF1278D1B98475B3254F2096CB64E23425C19C728225564), than you have on your page. So I assume there is mistake on your page?
![image](https://user-images.githubusercontent.com/2930419/120151395-7daf1180-c1ec-11eb-913d-c90584f4869d.png)

**To Reproduce**
- download https://updates.thycotic.net/proservices/powershell/tss_module/Thycotic.SecretServer.zip
- run Get-FileHash .\Thycotic.SecretServer.zip

1. Error/issue observed:
- hash is 625846DC9297963112BC2EE715BD35DF05055835FD1655DE01F3FDC08612CAAB

**Expected behavior**
- hash should be 6B33CD7D745971E6DEF1278D1B98475B3254F2096CB64E23425C19C728225564

**Environment (please complete the following information):**

***Secret Server***
Build/Version: 

***PowerShell version***

```powershell
<!-- paste output of $PSVersionTable -->
```

***Host information:***

[ ] Windows PowerShell 5.1
[ ] PowerShell 7+
[ ] PowerShell ISE
[ ] VS Code (Insiders/Stable)

**Additional context**

**Comment by wsmelton** [comment]
Thanks for the report!

The likely change was generating that file on a new machine when I last uploaded it. I'm working on moving the build process to a GH action. When I'm able to complete that processing I will publish the hash with the zip file and update docs.
