### ISSUE TITLE
[Bug] New-TssSecret with AutoChangeEnabled 

### ISSUE THREAD

**Issue by CermakPOI** [thycotic-ps/thycotic.secretserver#197]
**Describe the bug**
When creating an Secret with AutoChangeEnabled it throws an Error.
Unable to enable AutoChange on a Secret that is not enabled for RPC.

The Stub does NOT contain any Property that can enable RPC.

Of course the Template HAS RPC enabled! see $StubSecret below 
SecretTemplateId                   : **6003**
![image](https://user-images.githubusercontent.com/11089205/123394084-0710f400-d59f-11eb-98ac-da40fc881330.png)

How can i do this? It's been working with native rest api for ages. I just wanted to try if i can move my existing functions and workflows to your thycotic.secretserver Module.

**To Reproduce**
1. PowerShell script:

```powershell
$StubSecret = Get-TssSecretStub -SecretTemplateId $TemplateID -FolderID $FolderId -TssSession $global:POITSSSession
$StubSecret.name = $SecretName
$StubSecret.secretTemplateId = $templateId
$StubSecret.AutoChangeEnabled = "$True"
$NewSecret = New-TssSecret -TssSession $global:POITSSSession -SecretStub $StubSecret -ErrorAction Stop
```

1. Error/issue observed:

```powershell
System.Exception: {
  "errorCode": "API_AutoChangeEnableFailure",
  "message": "Unable to enable AutoChange on a Secret that is not enabled for RPC."
}

$StubSecret


SecretId                           : 0
AccessRequestWorkflowMapId         : 0
Active                             : True
AllowOwnersUnrestrictedSshCommands : False
AutoChangeEnabled                  : True
AutoChangeNextPassword             :
CheckedOut                         : False
CheckOutChangePasswordEnabled      : False
CheckOutEnabled                    : False
CheckOutIntervalMinutes            : -1
CheckOutMinutesRemaining           : -1
CheckOutUserDisplayName            :
CheckOutUserId                     : 0
DoubleLockId                       : 0
EnableInheritPermissions           : True
EnableInheritSecretPolicy          : True
FailedPasswordChangeAttempts       : 0
FolderId                           : 55
Id                                 : 0
IsDoubleLock                       : False
IsOutOfSync                        : False
IsRestricted                       : False
Items                              : {Machine, Username, Password, Application...}
LastHeartBeatCheck                 : 01.01.0001 00:00:00
LastHeartBeatStatus                : Pending
LastPasswordChangeAttempt          : 01.01.0001 00:00:00
LauncherConnectAsSecretId          : -1
Name                               :
OutOfSyncReason                    :
PasswordTypeWebScriptId            : -1
ProxyEnabled                       : False
RequiresApprovalForAccess          : False
RequiresComment                    : False
RestrictSshCommands                : False
SecretPolicyId                     : -1
SecretTemplateId                   : **6003**
SecretTemplateName                 : _Windows Account Local
SessionRecordingEnabled            : False
SiteId                             : -1
WebLauncherRequiresIncognitoMode   : False
```

**Expected behavior**
I would expect one of these behaviors

1. Use the RPC enabled flag from the Template
2. Allow me to set this flag on the new Secret or stub

**Environment (please complete the following information):**

***Secret Server***
Build/Version: 10.9.00000023

***PowerShell version***
5.1
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.18362.1593
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1593
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

***Host information:***

[x ] Windows PowerShell 5.1
[ ] PowerShell 7+
[ ] PowerShell ISE
[ ] VS Code (Insiders/Stable)

**Additional context**

**Comment by wsmelton** [comment]
The behavior you are seeing is from Secret Server and not directly related to the code or module itself.

> Use the RPC enabled flag from the Template

This is not accessible via the API.

> Allow me to set this flag on the new Secret or stub

The `AutoChangeEnabled` is used for that ability, as long as Secret Server has RPC enabled at the instance level.

All the OOB templates have `Enable Remote Password Changing` enabled by default. The RPC configuration on the Secret Server instance though has to be enabled as well for it to enable the feature.

![image](https://user-images.githubusercontent.com/11204251/123480243-ad70ef80-d5c7-11eb-8861-e5efa9ae0b9c.png)

The above info message shows up when RPC is not enabled for the instance of Secret Server:

![image](https://user-images.githubusercontent.com/11204251/123480321-cd081800-d5c7-11eb-9f6a-b156466035e7.png)

RPC at this time is not accessible over the REST API via public endpoints.

> How can i do this? It's been working with native rest api for ages

Please provide an example code doing this with native REST API calls.
