### ISSUE TITLE
Get-TssSecret should have easier access to items

### ISSUE THREAD

**Issue by bchap1n** [thycotic-ps/thycotic.secretserver#217]
### Summarize Functionality

In version 0.10.0 I could do this where the secret had fieldname 'password':
`(Get-TssSecret -id 1).password`

In version 0.47.0 I have to do something like this:
`((Get-ppTssSecret -id 1).items.where{$_.fieldname -eq 'password'}).itemvalue`

this makes the tool much harder to use in terminal. I would need to write complex wrappers that build custom objects for multiple template types just to get the old functionality. 

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
There are methods available for easy retrieval of slug values that can be found using `Get-Member` or the class documentation can be found here:  [Secret](https://thycotic-ps.github.io/thycotic.secretserver/about_topics/secrets/Secret.html#methods).

The method that can be used to get a field value:

```powershell
(Get-TssSecret ...).GetFieldValue('password')
```

The process noted from previous version was for pre-release and a new processing and object base was chosen for various reasons.

**Comment by bchap1n** [comment]
Thank you. I should have known to check out the methods. That's much better than my solution of using calculated fields in a wrapper:
```
[array]$calc = foreach($field in $secret.items.fieldname){@{name=$field;expression=[ScriptBlock]::create('($_.items.where{$_.fieldname -eq ' + "'$field'}).itemvalue")}}
$secret | select-object $calc
```

**Comment by wsmelton** [comment]
The script method option is one way of doing it and is not an uncommon practice. It adds a bit of overhead building that object out every time in the function and if you are piping to the function that adds up in timing. The classes used in this module are for pure performance reasons. Use of C# class takes all the fluff and overhead PowerShell has for building the properties and objects.

I am using the binding ability that PowerShell has though with the classes. Allowed me to get rid of hundreds of lines of code building those objects. The only requirement is the class needs the same property names as the API, and then PowerShell takes care of matching everything up to output the end result.

Current:

https://github.com/thycotic-ps/thycotic.secretserver/blob/c9a7707096d322682080a02f59af866ce7976335/src/functions/secrets/Get-TssSecret.ps1#L191-L196

The git history is not available on GitHub now as the file and folders have been renamed, but the code previously used in 0.10.0:

```powershell
                $outSecret = [PSCustomObject]@{
                    SecretId = $restResponse.id
                    TemplateId = $restResponse.secretTemplateId
                    FolderId = if ($restResponse.folderId -eq -1) { $null } else { $restResponse.folderId }
                    Active = $restResponse.active
                    LauncherConnectSecretId = if ($restResponse.launcherConnectAsSecretId -eq -1) { $null } else { $restResponse.launcherConnectAsSecretId }
                    Restricted = $restResponse.isRestricted
                    OutOfSync = $restResponse.isOutOfSync
                    OutOfSyncReason = $restResponse.outOfSyncReason
                    AutoChangeEnabled = $restResponse.autoChangeEnabled
                    AutoChangeNextPassword = $restResponse.AutoChangeNextPassword
                    ApprovalForAccessRequired = $restResponse.requiresApprovalForAccess
                    CommentRequired = $restResponse.requiresComment
                    Checkout = $restResponse.checkOutEnabled
                    CheckoutUserId = if ($restResponse.checkOutUserId -eq -1) { $null } else { $restResponse.checkOutUserId }
                    CheckoutIntervalMinutes = if ($restResponse.CheckoutIntervalMinutes -eq -1) { $null } else { $restResponse.checkOutIntervalMinutes }
                    CheckoutChangePassword = $restResponse.checkOutChangePasswordEnabled
                    AccessRequestWorkflowMapId = if ($restResponse.accessRequestWorkflowMapId -eq -1) { $null } else { $restResponse.accessRequestWorkflowMapId }
                    Proxy = $restResponse.proxyEnabled
                    SessionRecording = $restResponse.sessionRecordingEnabled
                    SSHCommandsRestricted = $restResponse.restrictSshCommands
                    SSHCommandsOwnersUnrestricted = $restResponse.allowOwnersUnrestrictedSshCommands
                    DoubleLock = $restResponse.isDoubleLock
                    DoubleLockId = if ($restResponse.doubleLockId -eq -1) { $null } else { $restResponse.doubleLockId }
                    InheritPermissions = $restResponse.enableInheritPermissions
                    InheritSecretPolicy = if ($restResponse.enableInheritSecretPolicy -eq -1) { $null } else { $restResponse.enableInheritSecretPolicy }
                    SiteId = $restResponse.siteId
                    SecretPolicyId = if ($restResponse.secretPolicyId -eq -1) { $null } else { $restResponse.secretPolicyId }
                    HeartbeatStatus = $restResponse.lastHeartBeatStatus
                    HeartbeatDate = [datetime]$restResponse.lastHeartBeatCheck
                    PasswordChangeFailedCount = $restResponse.failedPasswordChangeAttempts
                    PasswordChangeDate = [datetime]$restResponse.lastPasswordChangeAttempt
                    TemplateName = $restResponse.secretTemplateName
                }
                foreach ($itemDetail in $restResponse.items) {
                    $name = $itemDetail.fieldName
                    $value = $itemDetail.itemValue
                    $outSecret.PSObject.Properties.Add([PSNoteProperty]::new($name,$value))
                }
                $properties = $outSecret.PSObject.Properties | Sort-Object Name
                $final = [PSCustomObject]@{}
                foreach ($prop in $properties) {
                    $final.PSObject.Properties.Add([PSNoteProperty]::new($prop.Name,$prop.Value))
                }
                $final
```

The primary reason for taking the properties off the main object is for security reasons. Outputting a Secret from `Get-TssSecret` was going to be a given in most scripts, having the fields on the parent object would mean they are more easily logged by PSReadline and built-in logging for Windows PowerShell (aka operational log in Event Viewer). I didn't want the field data exposed that easily, so opted to keep it all under the `Items` property and add the method to force the user to make that choice of getting the value.

**Comment by bchap1n** [comment]
thanks for the context and the amazing work. better performance and security are appreciated.
