### ISSUE TITLE
Update-SecretDependency

### ISSUE THREAD

**Issue by lohash** [thycotic-ps/thycotic.secretserver#232]
### Summarize Functionality

This is much needed as there is no option to edit dependencies in the GUI currently.

### Endpoint
`POST /secret-dependencies`

### Additional Details
Very similar to creating a dependency but with some different args. The settings and dependencyTemplate args have tripped me up thus far as to how to successfully POST them as objects

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Not your code obviously but to give you an idea of what I tried, I used the "Create a Secret" example from [https://thycotic.force.com/support/s/article/REST-API-PowerShell-Scripts-Getting-Started](https://thycotic.force.com/support/s/article/REST-API-PowerShell-Scripts-Getting-Started) and modified the endpoint, etc. to try and update an existing dependency to run as a different privileged account:

```
try
{  
   $site = "https://URL"
   $api = "$site/api/v1"

   $creds = @{
       username = "user"
       password = "password"
       grant_type = "password"
   }

    $token = ""

    $response = Invoke-RestMethod "$site/oauth2/token" -Method Post -Body $creds
    $token = $response.access_token;

    Write-Host $token

    $headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
    $headers.Add("Authorization", "Bearer $token")

    #get
    $dependencyId = 13531
    $dependency = Invoke-RestMethod $api"/secret-dependencies/$dependencyId/" -Headers $headers
    
    #modify
    $timestamp = Get-Date

    $dependency.privilegedAccountSecretId = 1867
    $dependency.secretName = 'privileged account name'

    $dependencyArgs = $dependency | ConvertTo-Json

    #update
    Write-Host ""
    Write-Host "-----Update secret -----"

    $dependency = Invoke-RestMethod $api"/secret-dependencies/$dependencyId/" -Method Put -Body $dependencyArgs -Headers $headers -ContentType "application/json"

    $dependencyUpdate = $dependency | ConvertTo-Json
    Write-Host $dependencyUpdate #>
}
catch [System.Net.WebException]
{
    Write-Host "----- Exception -----"
    Write-Host  $_.Exception
    Write-Host  $_.Exception.Response.StatusCode
    Write-Host  $_.Exception.Response.StatusDescription
    $result = $_.Exception.Response.GetResponseStream()
    $reader = New-Object System.IO.StreamReader($result)
    $reader.BaseStream.Position = 0
    $reader.DiscardBufferedData()
    $responseBody = $reader.ReadToEnd()

    Write-Host $responseBody 
}
```

But I get the following error-

```
Invoke-RestMethod : {
  "message": "The request is invalid.",
  "modelState": {
    "args.settings[0].setting": [
      "An error has occurred."
    ],
    "args.dependencyTemplate.dependencyScanItemFields[0]": [
      "An error has occurred."
    ],
    "args.dependencyTemplate.dependencyScanItemFields[1]": [
      "An error has occurred."
    ]
  }
}
```

I tried also creating a PSobject with only the fields I want to change and just PUT'ing that, which gives Access Denied errors.

**Comment by wsmelton** [comment]
> This is much needed as there is no option to edit dependencies in the GUI currently.

You can fully edit Secret Dependencies via the GUI if you have the proper access/role permission.

**Comment by lohash** [comment]
I’m an Admin and can’t do anything except Delete, Run, etc. there is no Edit option. Is there a permission missing from the default Admin role?
  
  
  
    
  

  
  
>

**Comment by wsmelton** [comment]
You have access to the secret itself, if you are not an editor or owner you will not be allowed to edit any dependency. The RBAC is acknowledged for the REST API as well.

**Comment by lohash** [comment]
I am an Owner of the secrets in question. Just discovered the 3 dot menu that was hidden before I hovered over it lol
So perms aren't an issue on the API end, I'm assuming I just wasn't doing something correctly with those objects

**Comment by wsmelton** [comment]
A bug has been identified in this endpoint. Pending that being fixed this command will be added. You can verify or test using the codebase in the branch [thycotic-ps/thycotic.secretserver:secretpolicy-updatecmd](https://github.com/thycotic-ps/thycotic.secretserver/tree/secretpolicy-updatecmd)
