### ISSUE TITLE
New-TssSession - UseWindowsAuth not passing credentials properly

### ISSUE THREAD

**Issue by darkmoon55** [thycotic-ps/thycotic.secretserver#234]
### Verified issue does not already exist?

Yes

### What error did you receive

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>

### Please run the command using -Verbose

VERBOSE: Provided command parameters: New-TssSession -SecretServer: -UseWindowsAuth:$True -Verbose:$True
VERBOSE: UseWindowsAuth provided, setting URL segment to use winauthwebservices
VERBOSE: Setting start time for session: 09/06/2021 07:55:52
VERBOSE: Attempting to retrieve Secret Server host version
VERBOSE: Provided command parameters: Get-TssVersion -TssSession:TssSessionObject
VERBOSE: Performing the operation GET https://chn-vm-passwd/secretserver/winauthwebservices/api/v1/version
C:\Users\M21061\OneDrive - Microchip Technology Inc\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.54.0\parts\ProcessResponse.ps1 : <!DOCTYPE 
html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>
At C:\Users\username\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.54.0\functions\version\Get-TssVersion.ps1:53 char:33
+                 $restResponse = . $ProcessResponse $apiResponse
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://chn-vm-.../api/v1/version:String) [ProcessResponse.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1
 
VERBOSE: SecretServer host: https://chn-vm-passwd/secretserver
VERBOSE: ApiUrl: https://chn-vm-passwd/secretserver/winauthwebservices/api/v1
VERBOSE: Outputing final object

SecretServer        : https://chn-vm-passwd/secretserver
SecretServerVersion : 
ApiVersion          : api/v1
WindowsAuth         : winauthwebservices
ApiUrl              : https://servername/secretserver/winauthwebservices/api/v1
AccessToken         : 
RefreshToken        : 
TokenType           : WindowsAuth
ExpiresIn           : 0
StartTime           : 06/09/2021 07:55:52
TimeOfDeath         : 01/01/0001 00:00:00
Take                : 2147483647

### Provide a test case or steps to reproduce

After the  SecretServer V11 upgrade the following command is not working anymore.
Thycotic Support told me they cannot assist since it's a powershell issue.

New-TssSession -SecretServer "https://servername/secretserver" -UseWindowsAuth 

The Website is working perfect with Integrated Windows Authentication. Only the powershell module gives me the above error.

### Expected behavior

New TssSession should work as expected and get an access token.

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise)

### PowerShell Host Version

PSVersion                      5.1.19041.1151

**Comment by wsmelton** [comment]
I've pushed release 0.55.0 that from testing should have this fixed now

![image](https://user-images.githubusercontent.com/11204251/132406613-92225c43-0300-4440-903e-12ba5b6db9ee.png)

**Comment by darkmoon55** [comment]
Hi.
When I try to import-module with version 0.55.0 getting this dependency error now, .net framework 2.0/3.5 is enabled.

import-module thycotic.secretserver
import-module : Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot
find the file specified.
At line:1 char:1
+ import-module thycotic.secretserver
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand


Thanks

**Comment by wsmelton** [comment]
What is the latest version of .net you have installed on that machine?

**Comment by darkmoon55** [comment]
It’s showing these versions installed:


PSChildName                      Version        Release
-----------                      -------        -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084      528372
Full                             4.8.04084      528372
Client                           4.0.0.0
