### ISSUE TITLE
New-TssSession -UseWindowsAuth no longer works

### ISSUE THREAD

**Issue by devramdin** [thycotic-ps/thycotic.secretserver#247]
### Verified issue does not already exist?

Yes

### What error did you receive

New-TssSession -UseWindowsAuth no longer works at all on 0.59.0

No error is thrown regardless of the Secret Server URL passed.

The behavior is the same in Windows PowerShell and PowerShell Core.

### Please run the command using -Verbose

VERBOSE: Command invocation: New-TssSession -SecretServer: -UseWindowsAuth:True -Verbose:True
VERBOSE: UseWindowsAuth provided, setting URL segment to use winauthwebservices

### Provide a test case or steps to reproduce

New-TssSession -SecretServer https://foo.bar -UseWindowsAuth -Verbose

### Expected behavior

I reverted to 0.58.0 and UseWindowsAuth works as expected (a session is created without error using my actual URL).

New-TssSession -SecretServer https://foo.bar -UseWindowsAuth -Verbose
VERBOSE: Command invocation: New-TssSession -SecretServer: -UseWindowsAuth:True -Verbose:True
VERBOSE: UseWindowsAuth provided, setting URL segment to use winauthwebservices
VERBOSE: Setting start time for session: 10/26/2021 16:51:17
VERBOSE: Attempting to retrieve Secret Server host version
VERBOSE: Command invocation: Get-TssVersion -TssSession:TssSessionObject
VERBOSE: Performing the operation GET https://foo.bar/winauthwebservices/api/v1/version
ProcessResponse.ps1: C:\Users\admin\Documents\PowerShell\Modules\Thycotic.SecretServer\0.58.0\functions\version\Get-TssVersion.ps1:53
Line |
  53 |                  $restResponse = . $ProcessResponse $apiResponse
     |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |

VERBOSE: SecretServer host: https://foo.bar/
VERBOSE: ApiUrl: https://foo.bar/winauthwebservices/api/v1
VERBOSE: Outputing final object

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by chrisallennc** [comment]
My team is also seeing the same issue and can replicate it.

**Comment by peetrike** [comment]
Same with me, with Windows Integrated Authentication, the `New-TssSession` returns nothing.
