### ISSUE TITLE
Documentation for Output objects

### ISSUE THREAD

**Issue by miked1313** [thycotic-ps/thycotic.secretserver#254]
### Summarize Functionality

In the documentation the name of the object under Output is a link that goes nowhere.

https://thycotic-ps.github.io/thycotic.secretserver/commands/secrets/Get-TssSecret.html#outputs

For the Get-TssSecret page, the output Thycotic.PowerShell.Secrets.Secret has a link next to it which looks like a page heading anchor https://thycotic-ps.github.io/thycotic.secretserver/commands/secrets/Get-TssSecret.html#thycoticpowershellsecretssecret

Can examples be added of what the Thycotic.PowerShell.Secrets.Secret object contains?  This would also be useful for any other cmdlet outputs as well.

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by wsmelton** [comment]
We previously attempted to maintain the output help files via `about_*` files that could be read using `Get-Help`, but it was to much to maintain along with the codebase. The output types on the commands mirror the endpoint's model object that can be viewed in the REST API Guide. (e.g. `Thycotic.PowerShell.Secrets.Secret` is mirror of the output from `GET /v1/secrets/{id}` endpoint). 

PowerShell offers two methods that can be utilized to discover the output object properties:

- Utilize `Get-Member` (e.g. `<command call> | Get-Member -MemberType Properties,Methods`)
- Declare a new instance of the type, piping to `Format-List` (e.g. [Thycotic.PowerShell.Secrets.Secret]::new() | Format-List`)
