### ISSUE TITLE
Issue Adding Group Owner

### ISSUE THREAD

**Issue by jkratt** [thycotic-ps/thycotic.secretserver#255]
### Verified issue does not already exist?

Yes

### What error did you receive

Running the following command with local API account that has 'Admin' access

Add-TssSecretPermission -TssSession $TssSession -SecretId '1522' -GroupName 'Role CyberSecurity Tools Engineering Owners' -AccessRole Owner  -Verbose

VERBOSE: Command invocation: Add-TssSecretPermission -TssSession:TssSessionObject -SecretId:System.Int32[] -GroupName:Role
CyberSecurity Tools Engineering Owners -AccessRole:Role CyberSecurity Tools Engineering Owners -Verbose:True
VERBOSE: Command invocation: New-TssSecretPermission -GroupName:Role CyberSecurity Tools Engineering Owners
-TssSession:TssSessionObject -AccessRole:TssSessionObject -SecretId:System.Int32[] -DomainName:
VERBOSE: Command invocation: Search-TssSecret -TssSession:TssSessionObject
VERBOSE: Performing the operation GET
https://pam.aah.org/secretserver/api/v1/secrets?sortBy[0].direction=asc&sortBy[0].name=Name&take=2147483647&filter.includeRe
stricted=true
VERBOSE: Performing the operation POST https://pam.aah.org/secretserver/api/v1/secret-permissions with:
 System.Collections.Specialized.OrderedDictionary
C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\parts\ProcessResponse.ps1 : {
  "errorCode": "API_GenericException",
  "message": "Access Denied"
}
At C:\Program
Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\functions\secret-permissions\New-TssSecretPermission.ps1:101
char:41
+ ...                       $restResponse = . $ProcessResponse $apiResponse
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://pam.aah...ret-permissions:String) [ProcessResponse.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1

### Please run the command using -Verbose

Add-TssSecretPermission -TssSession $TssSession -SecretId '1522' -GroupName 'Role CyberSecurity Tools Engineerin
g Owners' -AccessRole Owner  -Verbose

VERBOSE: Command invocation: Add-TssSecretPermission -TssSession:TssSessionObject -SecretId:System.Int32[] -GroupName:Role
CyberSecurity Tools Engineering Owners -AccessRole:Role CyberSecurity Tools Engineering Owners -Verbose:True
VERBOSE: Command invocation: New-TssSecretPermission -GroupName:Role CyberSecurity Tools Engineering Owners
-TssSession:TssSessionObject -AccessRole:TssSessionObject -SecretId:System.Int32[] -DomainName:
VERBOSE: Command invocation: Search-TssSecret -TssSession:TssSessionObject
VERBOSE: Performing the operation GET
https://pam.aah.org/secretserver/api/v1/secrets?sortBy[0].direction=asc&sortBy[0].name=Name&take=2147483647&filter.includeRe
stricted=true
VERBOSE: Performing the operation POST https://pam.aah.org/secretserver/api/v1/secret-permissions with:
 System.Collections.Specialized.OrderedDictionary
C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\parts\ProcessResponse.ps1 : {
  "errorCode": "API_GenericException",
  "message": "Access Denied"
}
At C:\Program
Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\functions\secret-permissions\New-TssSecretPermission.ps1:101
char:41
+ ...                       $restResponse = . $ProcessResponse $apiResponse
+                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://pam.aah...ret-permissions:String) [ProcessResponse.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1

### Provide a test case or steps to reproduce

1. Creds stored in variable
2. Session opened

PS D:\Repos> $TssSession | fl *

SecretServer        : https://pam.aah.org/secretserver
SecretServerVersion :
ApiVersion          : api/v1
WindowsAuth         : winauthwebservices
ApiUrl              : https://pam.aah.org/secretserver/api/v1
AccessToken         : ****
RefreshToken        : ****
TokenType           : bearer
ExpiresIn           : 1199
StartTime           : 12/1/2021 12:30:45 PM
TimeOfDeath         : 12/1/2021 12:50:44 PM
Take                : 2147483647

### Expected behavior

Owner Group is added as Owner of User Group. 

### What Edition of Secret Server?

Professional

### What version of Secret Server

10.8

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.14393.4583                                                                               
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.14393.4583                                                                              
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1

**Comment by jkratt** [comment]
Want to correct Secret Server version. We are using version 11.0.000007

**Comment by tylerezimmerman** [comment]
@jkratt we just released a new version of the plug-in, can you confirm if this issue still exists?
