### ISSUE TITLE
get-tsssecretattachment does not accept path and id parameters in same parameter set

### ISSUE THREAD

**Issue by jagger** [thycotic-ps/thycotic.secretserver#256]
### Verified issue does not already exist?

Yes

### What error did you receive

Get-TssSecretAttachment -TssSession $SourceSession -Id $srce.Id -Slug public-key -path C:\temp\

Get-TssSecretAttachment: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

### Please run the command using -Verbose

 Get-TssSecretAttachment -TssSession $SourceSession -Id $srce.Id -Slug public-key -path C:\temp\ -verbose

Get-TssSecretAttachment: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

### Provide a test case or steps to reproduce

I modified get-tsssecretattachment.ps1 to add the following code after line 34
`              [Parameter(Mandatory, ValueFromPipelineByPropertyName, ParameterSetName = 'path')]`

after reloading the module my command worked as expected. 

### Expected behavior

Able to specify the secret ID and Path to output the file.

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by wsmelton** [comment]
You can try changing the following to see if it resolves it:

Change this line:

https://github.com/thycotic-ps/thycotic.secretserver/blob/74c7317f303f7c41f63bbc4d348383d1a8ebc941/src/functions/secrets/Get-TssSecretAttachment.ps1#L26

to:

```powershell
[cmdletbinding(DefaultParameterSetName = 'id')]
```

and then this line:

https://github.com/thycotic-ps/thycotic.secretserver/blob/74c7317f303f7c41f63bbc4d348383d1a8ebc941/src/functions/secrets/Get-TssSecretAttachment.ps1#L34

to:

```powershell
[Parameter(Mandatory, ValueFromPipelineByPropertyName)]
```
