### ISSUE TITLE
Any plans to support PowerShell's SecretManagement Vault Extension functionality?

### ISSUE THREAD

**Issue by MarkIannucci** [thycotic-ps/thycotic.secretserver#260]
### Summarize Functionality

I noticed that Microsoft [recently released SecretManagement](https://devblogs.microsoft.com/powershell/secretmanagement-and-secretstore-are-generally-available/) functionality which includes a secret vault extension functionality.  Does thycotic have any plans to incorporate that functionality in this or a different module?

I ask because we have a heterogenous environment with different teams managing secrets using different techniques and technologies over the years.  I would like to be able to write scripts that are indifferent to where the secrets are stored to make migration to a single solution (we own thycotic's) easier in the future.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Microsoft provides some details on how to build a SecretManagement Vault Extension in the [PowerShell SecretManagement repository](https://github.com/PowerShell/SecretManagement).

**Comment by wsmelton** [comment]
Previous stance was no direct plan to create or maintain a vault extension for the module. If someone else wanted to create one they are welcome to (module is open-source after all). Someone in the community has created an extension [SecretsManagement.SecretServer](https://www.powershellgallery.com/packages/SecretsManagement.SecretServer/).

I am no longer maintainer so whoever takes over the module within the ThycoticCentrify will have to decide.
