### ISSUE TITLE
SDK Client configuration Is Empty

### ISSUE THREAD

**Issue by DragonHiei** [thycotic-ps/thycotic.secretserver#261]
### Verified issue does not already exist?

Yes

### What error did you receive

The error I am receiving is: 

WARNING: Provided SecretServer host [https://RealServerNameGoesHere/secretserver/] does not match SDK Client configuration of [Not connected
]

I am not sure why but it looks like the imported sdk client configuration is empty, based on the warning output. I know there is some support for the client SDK in the PS module but not full support. So I apologize if this a known limitation, if so I'd love to be referred to a documentation that outlines them.

Thanks

### Please run the command using -Verbose

PS C:\Users\SomeUser> $session = New-TssSession -SecretServer 'https://RealServerNameGoesHere/secretserver/' -UseSdkClient -ConfigPath C:\PowerShell\Connection\Thycotic -verbose
VERBOSE: Command invocation: New-TssSession -SecretServer: -UseSdkClient:True -ConfigPath:C:\PowerShell\Connection\Thycotic -Verbose:True
VERBOSE: Processing SDK Client
VERBOSE: SDK Client raw response: Not connected

WARNING: Provided SecretServer host [https://RealServerNameGoesHere/secretserver/] does not match SDK Client configuration of [Not connected
]

### Provide a test case or steps to reproduce

PowerShell Session 1:
PS C:\Users\SomeUser> import-module c:\powershell\modules\thycotic.secretserver
PS C:\Users\SomeUser> Initialize-TssSdkClient -SecretServer 'https://RealServerNameGoesHere/secretserver' -RuleName RealRuleGoesHere -ConfigPath C:\PowerShell\Connection\Thycotic -OnboardingKey '... RealKeyGoesHere ...'
PS C:\Users\SomeUser> Test-TssSdkClient -SecretServer 'https://RealServerNameGoesHere/secretserver' -ConfigPath C:\PowerShell\Connection\Thycotic
True
PS C:\Users\SomeUser> $session = New-TssSession -SecretServer https://RealServerNameGoesHere/secretserver -UseSdkClient -ConfigPath C:\PowerShell\Connection\Thycotic

Open New PowerShell Session While Still Having the First Session Open:
PS C:\Users\SomeUser> import-module c:\powershell\modules\thycotic.secretserver
PS C:\Users\SomeUser> Test-TssSdkClient -SecretServer 'https://RealServerNameGoesHere/secretserver' -ConfigPath C:\PowerShell\Connection\Thycotic
False
PS C:\Users\SomeUser> $session = New-TssSession -SecretServer 'https://RealServerNameGoesHere/secretserver/' -UseSdkClient -ConfigPath C:\PowerShell\Connection\Thycotic -verbose
VERBOSE: Command invocation: New-TssSession -SecretServer: -UseSdkClient:True -ConfigPath:C:\PowerShell\Connection\Thycotic -Verbose:True
VERBOSE: Processing SDK Client
VERBOSE: SDK Client raw response: Not connected

WARNING: Provided SecretServer host [https://RealServerNameGoesHere/secretserver/] does not match SDK Client configuration of [Not connected
]

### Expected behavior

From All Subsequent PowerShell Session:
PS C:\Users\SomeUser> Test-TssSdkClient -SecretServer 'https://RealServerNameGoesHere/secretserver' -ConfigPath C:\PowerShell\Connection\Thycotic
True
PS C:\Users\SomeUser> $session = New-TssSession -SecretServer https://RealServerNameGoesHere/secretserver -UseSdkClient -ConfigPath C:\PowerShell\Connection\Thycotic

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by wsmelton** [comment]
Ensure your configuration path has no spaces in it. There is a limitation in that part of the `tss.exe` CLI with dealing with spaces.

**Comment by wsmelton** [comment]
Are you trying to create multiple sessions to the same SDK configuration? That will be a limitation of the CLI as I do not believe it supports multiple processes.

**Comment by wsmelton** [comment]
The expiration of the token aligns with the timeout configuration in SS.

There is no endpoint I'm aware of that allows explicitly to expire it.

**Comment by DragonHiei** [comment]
1. To confirm than there is no need to close the session (because we can't) when using client sdk to authentication to create a session?
2. Is there any known work around for having multiple processes using the same sdk config? such as creating a global variable?
