### ISSUE TITLE
Update-TssServerNode: The requested resource does not support http method 'PUT'."

### ISSUE THREAD

**Issue by vlariono** [thycotic-ps/thycotic.secretserver#262]
### Verified issue does not already exist?

Yes

### What error did you receive

```Powershell
C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\functions\server-nodes\Update-TssServerNode.ps1:95
Line |
  95 |  …                       $restResponse = . $ProcessResponse $apiResponse
     |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "message": "The requested resource does not support http method 'PUT'." }
```

### Provide a test case or steps to reproduce

Try to put a node into ReadOnly mode

```Powershell
Update-TssServerNode -TssSession $tss -NodeId <Id> -EnableReadonly -Verbose
```

### Expected behavior

HTTP POST method should be used instead of PUT

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

PSVersion                      7.2.1

**Comment by tylerezimmerman** [comment]
@vlariono we just released a new version of the plug-in, can you confirm if this issue still exists?

**Comment by vlariono** [comment]
Hi @tylerezimmerman,

This is a rather old issue. I've completed the project and won't be able to check  :-)
