### ISSUE TITLE
Find-TssSecret -IncludeSubFolders doesn't work

### ISSUE THREAD

**Issue by peetrike** [thycotic-ps/thycotic.secretserver#264]
### Verified issue does not already exist?

Yes

### What error did you receive

```
C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\parts\ProcessResponse.ps1 : {
  "message": "The request is invalid.",
  "modelState": {
    "filter.IncludeSubFolders": [
      "The value 'True)' is not valid for IncludeSubFolders."
    ]
  }
}
At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.5\functions\secrets\Find-TssSecret.ps1:273 char:33
+                 $restResponse = . $ProcessResponse $apiResponse
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://kapp.es...ubFolders=True):String) [ProcessResponse.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1
```

### Please run the command using -Verbose

```
VERBOSE: Command invocation: Find-TssSecret -TssSession:TssSessionObject -FolderId:TssSessionObject
-IncludeSubFolders:True -Verbose:True
VERBOSE: Filters: filter.folderId=113&filter.includeSubFolders=True)
VERBOSE: Performing the operation GET
```

### Provide a test case or steps to reproduce

```powershell
Find-TssSecret -TssSession $Session -FolderId 113 -IncludeSubFolders
```

### Expected behavior

It should return Secret references

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by TryTryAgain** [comment]
Same on Mac, it used to work (and I went tried a few different module versions and couldn't find one that still worked, it must have been something that changed server-side?):

VERBOSE: Command invocation: Find-TssSecret -TssSession:TssSessionObject -FolderId:TssSessionObject -Verbose:True -IncludeSubFolders:True
VERBOSE: Filters: filter.folderId=[HIDDEN_FOLDERID]&filter.includeSubFolders=True)
VERBOSE: Performing the operation GET https://vault/SecretServer/api/v1/secrets/lookup?sortBy[0].direction=asc&sortBy[0].name=Name&take=[HIDDEN_INT]&filter.includeRestricted=true&filter.folderId=[HIDDEN_FOLDERID]&filter.includeSubFolders=True)
ProcessResponse.ps1: /Users/user.name/.local/share/powershell/Modules/Thycotic.SecretServer/0.60.4/functions/secrets/Find-TssSecret.ps1:273:33
Line |
 273 |                  $restResponse = . $ProcessResponse $apiResponse
     |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {   "message": "The request is invalid.",   "modelState": {     "filter.IncludeSubFolders": [ 
     | "The value 'True)' is not valid for IncludeSubFolders."     ]   } }

WARNING: No secrets found
