### ISSUE TITLE
Thycotic.secretserver v0.60.6 not updated in PSGallery.

### ISSUE THREAD

**Issue by MaximoTrinidad** [thycotic-ps/thycotic.secretserver#268]
### Verified issue does not already exist?

No

### What error did you receive

Not able to download the latest version of "Thycotic.secretserver" Module v0.60.6 from the PSGallery.
I added a "Discussion" topic that no one is paying attention to.

Again since the upgrade to 11.1 all work done in using PowerShell with this module has impacted my time and effort 
assisting my colleagues.

after 8 days of the latest release .. is a simple question: 
When is this module going to be available in the PowerShell Gallery?

### Provide a test case or steps to reproduce

The following Cmdlet won't work;
Open-TssSecret
Set-TssSecret
Get-TssSecret
Get-TssSecretState
Invoke-TssSecretGeneratePassword
Close-TssSecret

### Expected behavior

Module cmdlets, after creating the TSS session functions for check-out/check-in/password-chg stop working after upgrade to 11.1

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

Issues are with both Windows PowerShell and PowerShell 7.2.1

**Comment by jagger** [comment]
Direct download link to PS module .zip has been updated to 60.6 

https://thyproservices.z20.web.core.windows.net/Thycotic.SecretServer.zip

**Comment by TryTryAgain** [comment]
Not really a powershell person. How do we use it after building it?

**Comment by MaximoTrinidad** [comment]
> Direct download link to PS module .zip has been updated to 60.6
> 
> https://thyproservices.z20.web.core.windows.net/Thycotic.SecretServer.zip

@jagger 

Our company have policies in place that don't allow download from GitHub. but they allow us to use PowerShell Gallery. By the way do you guys know that "SAPIIEN Technologies, Inc." have the "Module Manager tool that can push your module solution to PowerShell Gallery

Or, better yet! A faster solution:: Add the URL above to the list of the latest releases. This will make i much easier to grab and put it in the module folder. 

This will help a lot!!

:)

**Comment by MaximoTrinidad** [comment]
@jagger 

You guys are making it harder! My organization is blocking the link above... if you add the zip to the release section in GitHub makes it much easier to grab.

**Comment by MaximoTrinidad** [comment]
Simple enough!

After building the project, just copy the Thycotic.SectretServer module folder to both the Windows PowerShell 5.1 and thePowerShell 7.x into their Module folder in your user profile (which is the equivalent of installing a module using the " ..-Scope CurrentUser" .

Then, when opening a fresh PowerShell session an confirmed the module is listed in the "Get-Module -ListAvailable" cmdlet. After that you should be good to go

I hope this helps you,

Maximo Trinidad
Microsoft MVP - Cloud and Datacenter Management (PowerShell)

**Comment by TryTryAgain** [comment]
@MaximoTrinidad thanks, I'm doing this on Linux/Mac and have had no such luck. I've tried many different ways including building the project and extracting supplied rar/zip's... Moving the resulting Thycotic.SecretServer folders into each module directory from $Env:PSModulePath as well as multiple (after your suggestion), adding as is as well as adding into a subfolder within Thycotic.SecretServer with the version number. In some cases I'm able to get a -ListAvailable result back showing the correct 0.60.0 version but I'm subsequently either unable to import or if I'm able to import then I get a sea of red errors as if the cmdlets don't exist within the imported module. I'm stuck since we need this fix now that we migrated to the cloud server (our scripts and older version are working for our now read-only archive/onprem secret server).

**Comment by MaximoTrinidad** [comment]
HI Michael,

Sorry for the delay the easter bunny got me busy!!

As promise!

Here are the steps I use on my Linux that could possibly work on macOS:

The purpose is the install and make the module available to all users using the mac system:

  1.  Open PowerShell a Admin:

sudo pwsh


  1.  Remove previous version:

uninstall-module Thycotic.SecretServer -MinimumVersion 0.60.5


  1.  Get zipped file to your “Downloads” folder.
cd Downloads
wget https://thyproservices.z20.web.core.windows.net/Thycotic.SecretServer.zip


  1.  To unzipped module, execute:  (This will build the “Thycoptic.SecretServer” in the “shared” module folder.)

Expand-Archive ./Thycotic.SecretServer.zip -DestinationPath /usr/local/share/powershell/Modules/


  1.  Exit sudo pwsh:
Exit


  1.  Open pwsh current user:

pwsh


  1.  Confirm you see the module under the shared module folder:

Get-Module -list | Select name, version, path | Sort-Object name
gcm -Module Thycotic.SecretServer

If all of this works, then you’re good to go!
😊




From: Maximo Trinidad
Sent: Friday, April 15, 2022 12:11 PM
To: thycotic-ps/thycotic.secretserver ***@***.***>; thycotic-ps/thycotic.secretserver ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [thycotic-ps/thycotic.secretserver] Thycotic.secretserver v0.60.6 not updated in PSGallery. (Issue #268)

Hi Michael,

In both Linux and MacOS, you will need to identify where’s the userprofile path which doesn’t exist yet and PowerShell won’t build it for you during installation.

No!! “…Moving the resulting Thycotic.SecretServer folders into each module directory from $Env:PSModulePath…” the module need to exist in one location only. So only, if this machine is have multiple users then only use the macOS equivalent to linux main module path: /usr/local/share/powershell/Modules/”.

This will be enough for anyone using PowerShell when they logged in. I’m sure you’ll need the ‘sudo su’ in macOS to copy the folder over.

The following one-liner will list all existing modules so you can verify it was install correctly.
Get-Module -list | Select name, version, CompatiblePSEditions, path | Sort-Object name

I will give you a little more information later as I’m going to use my personal system to manually installed it.
I’m in the middle of work creating automation for VPV. 😊

**Comment by TryTryAgain** [comment]
Thank you! That does work, I've also since tested/verified success via:
```
curl -LJO https://thyproservices.z20.web.core.windows.net/Thycotic.SecretServer.zip
unzip ./Thycotic.SecretServer.zip > /dev/null
mv ./Thycotic.SecretServer $HOME/.local/share/powershell/Modules/
```

Didn't have success when using the rar from the releases section in this github project, even when mimicking/replicating the same versioned 0.60.6 subfolder etc. ... and also never had success with building from source even though the build seemed successful, moving the resulting data into place in the modules path never resulted in success for me :( 

Glad I'm able to get it working anyway, thanks for your help, sure hope they get the next version into PSGallery as normal.

**Comment by MaximoTrinidad** [comment]
Hi Michael,

This morning, I’ve been trying to convince have them to make the zipped module available under their assets section.
They are very stubborn about it!

Very disappointing!
☹

Have a GREAT DAY!

**Comment by MaximoTrinidad** [comment]
By the way, mission Accomplished!!

They added the zipped file to the Assets section.

***@***.***

From: Maximo Trinidad
Sent: Monday, April 18, 2022 10:53 AM
To: thycotic-ps/thycotic.secretserver ***@***.***>; thycotic-ps/thycotic.secretserver ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [thycotic-ps/thycotic.secretserver] Thycotic.secretserver v0.60.6 not updated in PSGallery. (Issue #268)


Hi Michael,

This morning, I’ve been trying to convince have them to make the zipped module available under their assets section.
They are very stubborn about it!

Very disappointing!
☹

Have a GREAT DAY!

**Comment by MaximoTrinidad** [comment]
Hi Michael,

In both Linux and MacOS, you will need to identify where’s the userprofile path which doesn’t exist yet and PowerShell won’t build it for you during installation.

No!! “…Moving the resulting Thycotic.SecretServer folders into each module directory from $Env:PSModulePath…” the module need to exist in one location only. So only, if this machine is have multiple users then only use the macOS equivalent to linux main module path: /usr/local/share/powershell/Modules/”.

This will be enough for anyone using PowerShell when they logged in. I’m sure you’ll need the ‘sudo su’ in macOS to copy the folder over.

The following one-liner will list all existing modules so you can verify it was install correctly.
Get-Module -list | Select name, version, CompatiblePSEditions, path | Sort-Object name

I will give you a little more information later as I’m going to use my personal system to manually installed it.
I’m in the middle of work creating automation for VPV. 😊
