### ISSUE TITLE
Get-TssSecretField returns field value enclosed in quotes

### ISSUE THREAD

**Issue by peetrike** [thycotic-ps/thycotic.secretserver#279]
### Verified issue does not already exist?

Yes

### What error did you receive

```powershell
Get-TssSecretField -TssSession $session -Id 12345 -Slug fieldslug
```
```
"some notes"
```

### Please run the command using -Verbose

```
VERBOSE: Command invocation: Get-TssSecretField -TssSession:TssSessionObject -Id:System.Int32[] -Slug:fieldslug -Verbose:True
VERBOSE: Performing the operation GET https://server/SecretServer/winauthwebservices/api/v1/secrets/12345/fields/notes with:

"some notes"

### Provide a test case or steps to reproduce

```powershell
Get-TssSecretField -TssSession $session -Id 12345 -Slug fieldslug
```

### Expected behavior

The field content should be returned as is, not with added quotes.

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

The same result is both in PowerShell 7 and Windows PowerShell 5.1

**Comment by tylerezimmerman** [comment]
@peetrike can you confirm that this issue is resolved?

**Comment by peetrike** [comment]
yes, now the result is without quotes
