### ISSUE TITLE
 Search-TssSecretDependency unable to Convert Value

### ISSUE THREAD

**Issue by jarred-Delinea** [thycotic-ps/thycotic.secretserver#282]
### Verified issue does not already exist?

Yes

### What error did you receive

PS C:\Windows\system32> Search-TssSecretDependency -TssSession $session -Id 63613

Cannot convert value "@{id=34356; secretId=63613; typeId=1; typeName=Application Pool; machineName=[QASVWBSVCAPP2.optumcc.com](https://qasvwbsvcapp2.optumcc.com/); serviceName=MHCWorkQueue; groupId=2535;

order=9; enabled=True; canTest=False; runResult=Success}" to type "Thycotic.PowerShell.SecretDependencies.Summary". Error: "Cannot convert the "@{id=34356;

secretId=63613; typeId=1; typeName=Application Pool; machineName=[QASVWBSVCAPP2.optumcc.com](https://qasvwbsvcapp2.optumcc.com/); serviceName=MHCWorkQueue; groupId=2535; order=9; enabled=True; canTest=False;

runResult=Success}" value of type "System.Management.Automation.PSCustomObject" to type "Thycotic.PowerShell.SecretDependencies.Summary"."

At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.7\functions\secret-dependencies\Search-TssSecretDependency.ps1:109 char:21

+ ...             [Thycotic.PowerShell.SecretDependencies.Summary[]]$restRe ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException

    + FullyQualifiedErrorId : InvalidCastConstructorException

### Provide a test case or steps to reproduce

PS C:\Windows\system32> Search-TssSecretDependency -TssSession $session -Id 63613

### Expected behavior

returns Secret Dependency info

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                   
----                           -----                                                                                                                   
PSVersion                      5.1.19041.1682                                                                                                          
PSEdition                      Desktop                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                 
BuildVersion                   10.0.19041.1682                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                         
WSManStackVersion              3.0                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                     
SerializationVersion           1.1.0.1

**Comment by tylerezimmerman** [comment]
@jarred-Delinea this will be resolved in the next release of the Secret Server API.
