### ISSUE TITLE
Get-TssSecretPolicy unable to Convert Value

### ISSUE THREAD

**Issue by joelutherjr** [thycotic-ps/thycotic.secretserver#283]
### Verified issue does not already exist?

Yes

### What error did you receive

PS C:\Users\JoeyLuther> $currentTargetPolicy = Get-TssSecretPolicy -TssSession $TssSession2 -Id $targetfolder.SecretPolicyId
Cannot convert value "@{secretPolicyId=32; secretPolicyName=Placeholder adm- policy; secretPolicyDescription=; active=True; secretPolicyItems=System.Object[]}" to type 
"Thycotic.PowerShell.SecretPolicies.Policy[]". Error: "Cannot create object of type "Thycotic.PowerShell.SecretPolicies.Policy". Cannot convert value 
"@{secretPolicyItemMapId=92; secretPolicyItemId=8; policyApplyType=Enforced; valueBool=True; valueInt=; <...>

### Please run the command using -Verbose

PS C:\Users\JoeyLuther> $currentTargetPolicy = Get-TssSecretPolicy -TssSession $TssSession2 -Id $targetfolder.SecretPolicyId -Verbose
VERBOSE: Command invocation: Get-TssSecretPolicy -TssSession:TssSessionObject -Id:System.Int32[] -Verbose:True
VERBOSE: Performing the operation GET http://jdl-app2/api/v1/secret-policy/32 with 
Cannot convert value "@{secretPolicyId=32; secretPolicyName=Placeholder adm- policy; secretPolicyDescription=; active=True; secretPolicyItems=System.Object[]}" to type 
"Thycotic.PowerShell.SecretPolicies.Policy[]". Error: "Cannot create object of type "Thycotic.PowerShell.SecretPolicies.Policy". Cannot convert value 
"@{secretPolicyItemMapId=92; secretPolicyItemId=8; policyApplyType=Enforced; valueBool=True; valueInt=; <...>

### Provide a test case or steps to reproduce

$currentTargetPolicy = Get-TssSecretPolicy -TssSession $TssSession2 -Id $targetfolder.SecretPolicyId 

### Expected behavior

Return secret policy items in respect to secret policy ID

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise)

### PowerShell Host Version

Name                           Value                                                                                                                                      
----                           -----                                                                                                                                      
PSVersion                      5.1.22621.285                                                                                                                              
PSEdition                      Desktop                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                    
BuildVersion                   10.0.22621.285                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                            
WSManStackVersion              3.0                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                        
SerializationVersion           1.1.0.1

**Comment by tylerezimmerman** [comment]
@joelutherjr this was resolved in #293 . This will be available in the PowerShell gallery the next time we do a release.
