### ISSUE TITLE
Adjustment to otpcode parameter on New-TssSession

### ISSUE THREAD

**Issue by dcherry88** [thycotic-ps/thycotic.secretserver#284]
### Summarize Functionality

The current iteration of the otpcode parameter for new-TssSession works for standard OTP scenarios, but I've seen cases where companies add additional codes onto their OTP system making the int value they represent exceeding the upper limit of an Int class. 

It would be nice to see the parameter allow larger number values to be used. 6 digit OTP codes with say, 4 additional numbers added at the end puts it in the billions value.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by tylerezimmerman** [comment]
Closing, this will be worked in #316
