### ISSUE TITLE
Find-TssUser -FindText has no effect

### ISSUE THREAD

**Issue by TryTryAgain** [thycotic-ps/thycotic.secretserver#285]
### Verified issue does not already exist?

Yes

### What error did you receive

No error, instead the response contains all users within the domain... when it should be narrowed down based on -FindText

### Please run the command using -Verbose

```
VERBOSE: Command invocation: Find-TssUser -Verbose:True -TssSession:TssSessionObject -Field:TssSessionObject -FindText:demo
VERBOSE: Filters: filter.FindFields=Username&filter.FindFields=Email&filter.FindText=demo
VERBOSE: Performing the operation GET https://omc.secretservercloud.eu/api/v1/users/lookup?sortBy[0].direction=asc&sortBy[0].name=DisplayName&take=[10-digits-removed]&filter.FindFields=Username&filter.FindFields=Email&filter.FindText=demo with: 
```

### Provide a test case or steps to reproduce

Run the command above and it returns all users instead of the user(s) that contain demo in the name. I've of course used specific names/emails instead of "demo" and still get the same results: all users are displayed instead of the expected/specified -FindText data

### Expected behavior

Expected -FindText to work as the documentation states it should: That supplying -FindText would "Return a list of all users with "demo" in the username or email"

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

EA release

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by tylerezimmerman** [comment]
@TryTryAgain this has been resolved in #292 and has been pushed to the Dev Branch and will be included in the next release to the PowerShell Gallery.
