### ISSUE TITLE
Get-TssSecretStub returns API_InvalidTemplate when using the "Password" template

### ISSUE THREAD

**Issue by jeffreynelson** [thycotic-ps/thycotic.secretserver#286]
### Verified issue does not already exist?

Yes

### What error did you receive

C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.7\parts\ProcessResponse.ps1 : {
  "errorCode": "API_InvalidTemplate",
  "message": "Provided Secret Template is invalid."
}
At C:\Program 
Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.7\functions\secrets\Get-TssSecretStub.ps1:73 
char:33
+                 $restResponse = . $ProcessResponse $apiResponse
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://secrets...retTemplateId=2:String) [ProcessResponse.ps1], 
    Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1

### Please run the command using -Verbose

VERBOSE: Command invocation: Get-TssSecretStub -TssSession:TssSessionObject -SecretTemplateId:TssSessionObject 
-Verbose:True
VERBOSE: Performing the operation GET https://secretserver.ad.trs.state.tx.us/winauthwebservices/api/v1/secrets
/stub?secretTemplateId=2
C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.7\parts\ProcessResponse.ps1 : {
  "errorCode": "API_InvalidTemplate",
  "message": "Provided Secret Template is invalid."
}
At C:\Program 
Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.7\functions\secrets\Get-TssSecretStub.ps1:73 
char:33
+                 $restResponse = . $ProcessResponse $apiResponse
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://secrets...retTemplateId=2:String) [ProcessResponse.ps1], 
    Exception
    + FullyQualifiedErrorId : ResultError,ProcessResponse.ps1
 

### Provide a test case or steps to reproduce

$session = New-TssSession -SecretServer https://SecretServer.ad.trs.state.tx.us -UseWindowsAuth 
$TemplateID = 2     # Password
$Template = Get-TssSecretTemplate -TssSession $session -SecretTemplateId $TemplateId
$Stub = Get-TssSecretStub -TssSession $session  -SecretTemplateId $Template.Id 

### Expected behavior

We should get back a stub object to use to create a new secret. 

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise)

### PowerShell Host Version

Name                           Value                                                                          
----                           -----                                                                          
PSVersion                      5.1.19041.1682                                                                 
PSEdition                      Desktop                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                        
BuildVersion                   10.0.19041.1682                                                                
CLRVersion                     4.0.30319.42000                                                                
WSManStackVersion              3.0                                                                            
PSRemotingProtocolVersion      2.3                                                                            
SerializationVersion           1.1.0.1

**Comment by jeffreynelson** [comment]
The secret server version reported from the $Session is 11.1.000012

**Comment by jeffreynelson** [comment]
Also, the following does not return the Password template.

Search-TssSecretTemplate -TssSession $session -SearchText "Password"

**Comment by tylerezimmerman** [comment]
@jeffreynelson we were unable to replicate this bug. 

We have used password template and created a stub using below command.

![image](https://user-images.githubusercontent.com/100804646/191841497-5fca1486-5640-491e-aefb-f0e45c07bada.png)

Then we have used below steps to create a new secret by using the stub.

![image](https://user-images.githubusercontent.com/100804646/191841515-0630f279-2ba2-433f-b354-e20f7d24bcf7.png)


Secret Server 

We can see the new secret created successfully by using the password template.

![image](https://user-images.githubusercontent.com/100804646/191841542-ef119b01-5456-4ee1-b27e-43b629972c64.png)


If this is still an problem, please reopen the issue with additional steps to reproduce.
