### ISSUE TITLE
Add-TssFolderPermission unable to Convert Value (workaround available)

### ISSUE THREAD

**Issue by joelutherjr** [thycotic-ps/thycotic.secretserver#287]
### Verified issue does not already exist?

Yes

### What error did you receive

Returns Unable to Convert Value... error on cmdlet

![image](https://user-images.githubusercontent.com/81325707/180016433-f4f8d6fe-d879-49fe-bbcb-f9d090712348.png)

### Please run the command using -Verbose

Same error

### Provide a test case or steps to reproduce

#$cred = get-credential #This API account has Owner permissions on target folder
#$tsssession = New-TssSession -SecretServer https://<redacted> -Credential $cred

Add-TssFolderPermission -TssSession $TssSession -FolderId 618 -Group Administrators -FolderRole Owner -SecretRole Owner

### Expected behavior

Group to be added to folder permissions on target folder.

Workaround available:
New-TssFolderPermission, though this requires a Group/User ID instead of name.

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.0

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise)

### PowerShell Host Version

Name                           Value                                                                                                 
----                           -----                                                                                                 
PSVersion                      5.1.22621.285                                                                                         
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.22621.285                                                                                        
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1

**Comment by tylerezimmerman** [comment]
@joelutherjr this will be resolved in an upcoming release of the Secret Server API.
