### ISSUE TITLE
   Export-TssReport errors out when creating file

### ISSUE THREAD

**Issue by ConagherL** [thycotic-ps/thycotic.secretserver#311]
### Verified issue does not already exist?

No

### What error did you receive

When running the command you return  "Internal Server Error"

```
C:\Users\XXX\OneDrive- Delinea\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.8\parts\ErrorHandling.ps1 : Internal Server Error
At C:\Users\XXX\OneDrive - Delinea\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.8\functions\reports\Export-TssReport.ps1:107 char:17
+                 . $ErrorHandling $err
+                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://blt.sec.../reports/export:String) [ErrorHandling.ps1], Exception
    + FullyQualifiedErrorId : `ResultError,ErrorHandling.ps1
```

### Please run the command using -Verbose

```
VERBOSE: Command invocation: Export-TssReport -TssSession:TssSessionObject -ReportId:TssSessionObject -Verbose:True
VERBOSE: Performing the operation POST https://XXX/api/v1/reports/export with:
{
    "format":  "csv",
    "delimiter":  ",",
    "id":  "116"
}
WARNING: Issue getting report data
C:\Users\XXX\OneDrive - Delinea\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.8\parts\ErrorHandling.ps1 : Internal Server Error
At C:\Users\XXX\OneDrive - Delinea\Documents\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.8\functions\reports\Export-TssReport.ps1:107 char:17
+                 . $ErrorHandling $err
+                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (https://blt.sec.../reports/export:String) [ErrorHandling.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ErrorHandling.ps1
```

### Provide a test case or steps to reproduce

Collect the ID of a report. Then run Export-tssReport against that ID

### Expected behavior

Export report and create file in the specified path

### What Edition of Secret Server?

Platinum

### What version of Secret Server

EA release

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.22621.608
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.608
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by tylerezimmerman** [comment]
@ConagherL we just released a new version of the plug-in, can you confirm if this issue still exists?

**Comment by jagger** [comment]
Can not reproduce in current version
