### ISSUE TITLE
Search-TSSSecret - Thycotic.PowerShell.Secrets.Summary

### ISSUE THREAD

**Issue by R-STR** [thycotic-ps/thycotic.secretserver#321]
### Verified issue does not already exist?

Yes

### What error did you receive

Error: "Cannot convert the "@{id=; name=; secretTemplateId=; secretTemplateName=; folderId=; folderPath=; siteId=; active=; checkedOut=; isRestricted=; isOutOfSync=; 
outOfSyncReason=; lastHeartBeatStatus=; lastPasswordChangeAttempt=; responseCodes=; lastAccessed=; extendedFields=; checkOutEnabled=; autoChangeEnabled=; doubleLockEnabled=; requiresApproval=; requiresComment=; inheritsPermissions=; hidePassword=; createDate=; 
daysUntilExpiration=; hasLauncher=}" value of type "System.Management.Automation.PSCustomObject" to type "Thycotic.PowerShell.Secrets.Summary"."
At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.60.8\functions\secrets\Search-TssSecret.ps1:274 char:17

### Please run the command using -Verbose

VERBOSE: Command invocation: Search-TssSecret -TssSession:TssSessionObject -FolderId:TssSessionObject -Verbose:True
VERBOSE: Filters: filter.folderId=
VERBOSE: Performing the operation GET https:// /api/v1/secrets?sortBy[0].direction=asc&sortBy[0].name=Name&take=2147483647&filter.includeRestricted=true&filter.folderId=
Cannot convert value

### Provide a test case or steps to reproduce

Search-TSSSecret

### Expected behavior

Return list of array objects

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

EA release

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

5.1

**Comment by MrM1y4g1** [comment]
I discovered this issue as well and implemented a quick fix in our cached module, basically we're ignoring the new folderPath that is being returned by the API. An actually fix would be to add the property to the class.

**Comment by VirtuallyDan** [comment]
I'm hitting this as well. It was working late last week.

@MrM1y4g1 Can you please share the work around, until we get an official release?

Thx!

**Comment by VirtuallyDan** [comment]
That works like a Champ!

Thx for the quick reply!

**Comment by rkendrick486** [comment]
Came here to state this is still a problem for me after updating. The above suggestions worked as a band-aid.

**Comment by wlodge-WM** [comment]
OK so my code above neuters the output much more than is necessary.  @MrM1y4g1 had the right idea, but it was missing the "*" after Select-Object, so it didn't work for me originally.  Adding that in works.  Line 274 should instead read:
[Thycotic.PowerShell.Secrets.Summary[]] ($restResponse.records | Select-Object * -ExcludeProperty folderPath)

**Comment by wlodge-WM** [comment]
This appears to be resolved as of 0.61.0.  Thank you!
