### ISSUE TITLE
Get-TssSecretField can no longer retrieve file objects in 0.60.9

### ISSUE THREAD

**Issue by justinmetz** [thycotic-ps/thycotic.secretserver#325]
### Verified issue does not already exist?

Yes

### What error did you receive

WARNING: Issue getting field [private-key] on secret [1129]
C:\Users\User\Downloads\thycotic.secretserver.0.60.9\parts\ErrorHandling.ps1 : You cannot call a method on a null-valued expression.
At C:\Users\User\Downloads\thycotic.secretserver.0.60.9\functions\secrets\Get-TssSecretField.ps1:176 char:21
+                     . $ErrorHandling $err
+                     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (xxxxx/private-key:String) [ErrorHandling.ps1], Exception
    + FullyQualifiedErrorId : ResultError,ErrorHandling.ps1

### Please run the command using -Verbose

Running this cmdlet in Verbose did not provide any more information than above

### Provide a test case or steps to reproduce

Run something similar to -> Get-TssSecretField -TssSession $session -Id $ThycoticResourceID -Slug 'private-key' -OutFile 'C:\Temp\private-key.pem' -Verbose

The change in this commit is causing the issue -> https://github.com/thycotic-ps/thycotic.secretserver/commit/e5cba81e7903943765a331af036039d39ea6ddde

### Expected behavior

The cmdlet should return a "OutFile" that is the contents of the file object property of the particular ID being requested.  This works as expected in V0.60.8 but stopped working in V0.60.9.

The changes in this commit is causing the issue, I took out the new lines and it works as it did in V0.60.8 -> https://github.com/thycotic-ps/thycotic.secretserver/commit/e5cba81e7903943765a331af036039d39ea6ddde

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

EA release

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.19041.2673                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.19041.2673                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1

**Comment by tylerezimmerman** [comment]
This has been fixed in version 0.61.0.
