### ISSUE TITLE
Search-TssSecret unexpected new properties "checkOutUserId" & "checkOutUserName"

### ISSUE THREAD

**Issue by MrM1y4g1** [thycotic-ps/thycotic.secretserver#350]
### Verified issue does not already exist?

Yes

### What error did you receive

The property 'checkOutUserId' was not found for the 'Thycotic.PowerShell.Secrets.Summary' object. The settable properties are: [SecretId <System.Int32>], [SecretName <System.String>], [Active <System.Boolean>], [AutoChangeEnabled <System.Boolean>], [CheckedOut <System.Boolean>], [CheckOutEnabled <System.Boolean>], [CreateDate <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [DaysUntilExpiration <System.Int32>], [DoubleLockEnabled <System.Boolean>], [ExtendedFields <Thycotic.PowerShell.Secrets.SummaryExtendedField[]>], [FolderId <System.Int32>], [HasLauncher <System.Boolean>], [HidePassword <System.Boolean>], [Id <System.Int32>], [InheritsPermissions <System.Boolean>], [IsOutOfSync <System.Boolean>], [OutOfSyncReason <System.String>], [IsRestricted <System.Boolean>], [LastAccessed <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [LastHeartbeatStatus <Thycotic.PowerShell.Enums.SecretHeartbeatStatus>], [LastPasswordChangeAttempt <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [Name <System.String>], [folderPath <System.String>], [RequiresApproval <System.Boolean>], [RequiresComment <System.Boolean>], [SecretTemplateId <System.Int32>], [SecretTemplateName <System.String>], [SiteId <System.Int32>], [ResponseCodes <System.String[]>].

The property 'checkOutUserName' was not found for the 'Thycotic.PowerShell.Secrets.Summary' object. The settable properties are: [SecretId <System.Int32>], [SecretName <System.String>], [Active <System.Boolean>], [AutoChangeEnabled <System.Boolean>], [CheckedOut <System.Boolean>], [CheckOutEnabled <System.Boolean>], [CreateDate <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [DaysUntilExpiration <System.Int32>], [DoubleLockEnabled <System.Boolean>], [ExtendedFields <Thycotic.PowerShell.Secrets.SummaryExtendedField[]>], [FolderId <System.Int32>], [HasLauncher <System.Boolean>], [HidePassword <System.Boolean>], [Id <System.Int32>], [InheritsPermissions <System.Boolean>], [IsOutOfSync <System.Boolean>], [OutOfSyncReason <System.String>], [IsRestricted <System.Boolean>], [LastAccessed <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [LastHeartbeatStatus <Thycotic.PowerShell.Enums.SecretHeartbeatStatus>], [LastPasswordChangeAttempt <System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]>], [Name <System.String>], [folderPath <System.String>], [RequiresApproval <System.Boolean>], [RequiresComment <System.Boolean>], [SecretTemplateId <System.Int32>], [SecretTemplateName <System.String>], [SiteId <System.Int32>], [ResponseCodes <System.String[]>].

### Please run the command using -Verbose

VERBOSE: Command invocation: Search-TssSecret -TssSession:TssSessionObject -SecretTemplateId:TssSessionObject -Verbose:True
VERBOSE: Filters: filter.secretTemplateId=6079
VERBOSE: Performing the operation GET https://[REDACTED].secretservercloud.eu/api/v1/secrets?sortBy[0].direction=asc&sortBy[0].name=Name&take=2147483647&filter.includeRestricted=true&filter.secretTemplateId=6079

### Provide a test case or steps to reproduce

```
# First let's check if the basic credentails is set, if not prompt the user to fill it out.
if( $null -eq $Credentials ) {
    $Credentials = Get-Credential
    $TycoticUrl = Read-Host
}

# Secondly let's load the latest Thycotic.SecretServer module
Import-Module "$($PSScriptRoot)\0.61.1\Thycotic.SecretServer.psd1"

# Thirdly let's create the Thycotic.SecretServer session
$TycoticSession = New-TssSession -SecretServer $TycoticUrl -Credential $Credentials

# And lastly let's retrive a secret from the Thycotic.SecretServer session
$TycoticSecrets = Search-TssSecret -TssSession $TycoticSession -SecretTemplateId 6079 -Verbose

```
### Expected behavior

Expected return of object with secret.

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by MrM1y4g1** [comment]
Tempoary fix for me has been to alter Search-TssSecret.ps1:274 with the following line to ignore the new values no yet mirrored in the code.
`[Thycotic.PowerShell.Secrets.Summary[]] ( $restResponse.records | Select-Object -ExcludeProperty "checkOutUserId", "checkOutUserName" )`

**Comment by rkendrick486** [comment]
This is broken for me as well. Tried the workaround listed above and it didn't work, however I took what someone provided the last time this broke and it worked -

[Thycotic.PowerShell.Secrets.Summary[]] ($restResponse.records | Select-Object ID, Name, SecretName, FolderID, SecretTemplateName, Active, LastHeartbeatStatus, LastPasswordChangeAttempt, DaysUntilExpiration)

**Comment by wlodge-WM** [comment]
> Tempoary fix for me has been to alter Search-TssSecret.ps1:274 with the following line to ignore the new values no yet mirrored in the code. `[Thycotic.PowerShell.Secrets.Summary[]] ( $restResponse.records | Select-Object -ExcludeProperty "checkOutUserId", "checkOutUserName" )`

To get this to work for me, I had to add a * after Select-Object:
[Thycotic.PowerShell.Secrets.Summary[]] ( $restResponse.records | Select-Object * -ExcludeProperty "checkOutUserId", "checkOutUserName" )

**Comment by jagger** [comment]
I'll extend the class to add these properties

**Comment by jagger** [comment]
```
PS>  Search-TssSecret -TssSession $session | Select-Object -Property SecretId,SecretTemplateName,checkOutUserId,checkOutUserName -First 3

SecretId SecretTemplateName checkOutUserId checkOutUserName
-------- ------------------ -------------- ----------------
    9892 SSH Key                        -1
    4046 Windows Account                 8 Rob Jagger
    4173 Windows Account                -1

PS>
```
