### ISSUE TITLE
New-TssMetadataField, Update-TssMetadataField, Update-TssMetadataSection error

### ISSUE THREAD

**Issue by drewzinl** [thycotic-ps/thycotic.secretserver#352]
### Verified issue does not already exist?

Yes

### What error did you receive

When running any of those commands I get,

WARNING: Issue creating Metadata Field on Item [7]
ErrorHandling.ps1: C:\Program Files\PowerShell\7\Modules\Thycotic.SecretServer\functions\metadata\New-TssMetadataField.ps1:156
Line |
 156 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using
     | ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.OverloadDefinitions.

### Please run the command using -Verbose

New-TssMetadataField @newMetaParams -verbose
VERBOSE: Command invocation: New-TssMetadataField -Verbose:True -FieldName:Employee ID -TssSession:TssSessionObject -SectionId:TssSessionObject -ItemId:TssSessionObject -ItemType:TssSessionObject -FieldValue:2021 -FieldDataType:2021
VERBOSE: Performing the operation POST https://delprd01.inl.gov/secretserver/api/v1/metadata/User/7 with:
{
  "data": {
    "metadataFieldSectionId": 2,
    "valueNumber": "2021",
    "metadataFieldName": "Employee ID",
    "fieldDataType": "Number"
  }
}

VERBOSE: Performing the operation "POST https://delprd01.inl.gov/secretserver/api/v1/metadata/User/7 with:
{
  "data": {
    "metadataFieldSectionId": 2,
    "valueNumber": "2021",
    "metadataFieldName": "Employee ID",
    "fieldDataType": "Number"
  }
}
" on target "Item ID: 7".
WARNING: Issue creating Metadata Field on Item [7]
ErrorHandling.ps1: C:\Program Files\PowerShell\7\Modules\Thycotic.SecretServer\functions\metadata\New-TssMetadataField.ps1:156
Line |
 156 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using
     | ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.OverloadDefinitions.

### Provide a test case or steps to reproduce

$newMetaParams = @{
    TssSession = $session
    ItemId = 7
    ItemType = 'User'
    SectionId = 2
    FieldName = 'Employee ID'
    FieldDataType = 'Number'
    FieldValue = '2021'
}
New-TssMetadataField @newMetaParams

### Expected behavior

Create new metadata field.

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.4

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by tylerezimmerman** [comment]
@drewzinl we will be addressing this issue in the next release.

**Comment by tylerezimmerman** [comment]
Related to #353

**Comment by tylerezimmerman** [comment]
@drewzinl This should be resolved in the 0.61.2 release, which is now available in the Powershell Gallery

**Comment by drewzinl** [comment]
Thanks!
