### ISSUE TITLE
new-TSSsecret Not working on latest version v0.61.1

### ISSUE THREAD

**Issue by indrani143** [thycotic-ps/thycotic.secretserver#353]
### Verified issue does not already exist?

Yes

### What error did you receive

ErrorHandling.ps1: C:\Users\imanjula\OneDrive - RWS\Documents\PowerShell\Modules\Th
/ycotic.SecretServer\0.61.1\functions\secrets\New-TssSecret.ps1:84
Line |
  84 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using
     | ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.OverloadDefinitions.
/

### Please run the command using -Verbose

  84 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using
     | ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.OverloadDefinitions.

### Provide a test case or steps to reproduce

with lower version of SS 0.61.0 is good

### Expected behavior

new secret would be created

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

7.5

**Comment by tylerezimmerman** [comment]
@indrani143 we will be addressing this issue in the next release.

**Comment by tylerezimmerman** [comment]
@indrani143  This should be resolved in the 0.61.2 release, which is now available in the Powershell Gallery
