### ISSUE TITLE
The module does not load in PowerShell 5.1

### ISSUE THREAD

**Issue by peetrike** [thycotic-ps/thycotic.secretserver#357]
### Verified issue does not already exist?

Yes

### What error did you receive

```
import-module : The version of Windows PowerShell on this computer is '5.1.19041.2673'. The module 'Thycotic.SecretServer' requires a minimum Windows PowerShell version of '7.2.11' to run. Verify that you have the minimum required version of Windows PowerShell installed, and then try again.
```

### Provide a test case or steps to reproduce

import-module Thycotic.SecretServer

### Expected behavior

The [documentation](https://thycotic-ps.github.io/thycotic.secretserver/getting_started/install.html) still states that PowerShell 5.1 is supported

### What Edition of Secret Server?

Platinum

### What version of Secret Server

11.3

### What PowerShell host was used when producing this error

Windows PowerShell (powershell)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by peetrike** [comment]
it seems, that [ChangeLog](https://github.com/thycotic-ps/thycotic.secretserver/blob/main/CHANGELOG.md) is not any more updated.  So, updating to latest module version renders module unusable under PowerShell 5.1

**Comment by peetrike** [comment]
unfortunately that doesn't prevent update under PowerShell 5.1.  The error occurs only after update.  And when this module is marked as required in scripts, the problem is somewhat hidden and occurs only after the module is explicitly loaded.

It would be nice, if module metadata could contain release notes or at least link to up to date release notes...

**Comment by tylerezimmerman** [comment]
#358
