### ISSUE TITLE
Get-TssSecretField truncates last character of attachment/file

### ISSUE THREAD

**Issue by chrisallennc** [thycotic-ps/thycotic.secretserver#360]
### Verified issue does not already exist?

Yes

### What error did you receive

When running Get-TssSecretField to get a file attached to the secret it is truncating off the last character on the string that's being returned. If we provide a path using the -OutFile parameter the resultant file has the correct content. For our specific case it's a certificate pem file and it's removing the last "-". So instead of the last line being "-----END CERTIFICATE-----" it's "-----END CERTIFICATE----".

Module version is 0.61.2. This appears to be similar/related to https://github.com/thycotic-ps/thycotic.secretserver/issues/325 but not the same issue.

### Please run the command using -Verbose

VERBOSE: Command invocation: Get-TssSecretField -Id:System.Int32[] -Slug:public-key -Verbose:True -TssSession:TssSessionObject
VERBOSE: Performing the operation GET https://<server>/secretserver/winauthwebservices/api/v1/secrets/<secret_id>/fields/<field_name> with:
<content>

### Provide a test case or steps to reproduce

$certificateSecret = Get-TssSecret -TssSession $tssSession -Path $secretPath
$certificateContent = Get-TssSecretField -TssSession $tssSession -Id $certificateSecret.Id -Slug "<field_name>"
# $certificateContent is a string with the last line missing the final "-"

Get-TssSecretField -Id $certificateSecret.Id -Slug "<field_name>" -OutFile $filePath
# resultant file at $filePath has correct content

### Expected behavior

String returned by Get-TssSecretField should not be missing last character of file content

### What Edition of Secret Server?

Professional

### What version of Secret Server

11.3

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.5
PSEdition                      Core
GitCommitId                    7.3.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by gaurava-delinea** [comment]
@chrisallennc  @tylerezimmerman 

I tried to reproduce the bug but not able to replicate it. you can see the below screenshot. 

![image](https://github.com/thycotic-ps/thycotic.secretserver/assets/108067029/2317c745-f066-479a-8a89-967638b86e4a)
