### ISSUE TITLE
New-TssSecret Errors Out.

### ISSUE THREAD

**Issue by coolidzwergon** [thycotic-ps/thycotic.secretserver#363]
### Verified issue does not already exist?

Yes

### What error did you receive

New-TssSecret in the api produces the error "A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles".  Research suggests that there is a circular reference in the Invoke-TssApi function.  The documentation for creating a secret with the API also fails with the same error.  [Secrets · Thycotic.SecretServer Module (thycotic-ps.github.io)](https://thycotic-ps.github.io/thycotic.secretserver/getting_started/working_with/secrets.html)

### Please run the command using -Verbose

ErrorHandling.ps1: C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.61.1\functions\secrets\New-TssS
ecret.ps1:84:17
Line |
  84 |                  . $ErrorHandling $err
     |                  ~~~~~~~~~~~~~~~~~~~~~
     | A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than
     | the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support
     | cycles. Path:
     | $.Members.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Valu
e.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.Value.V
alue.Value.Value.Value.Value.Value.Value.Value.V

### Provide a test case or steps to reproduce

The documentation for creating a secret with the API also fails with the same error.  [Secrets · Thycotic.SecretServer Module (thycotic-ps.github.io)](https://thycotic-ps.github.io/thycotic.secretserver/getting_started/working_with/secrets.html)

### Expected behavior

New secret gets created.

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      3      5

**Comment by gaurava-delinea** [comment]
@coolidzwergon
This issue has been fixed in the [v0.61.2]. now the latest version is [v0.61.3].
Please use the latest version.

cc @tylerezimmerman
