### ISSUE TITLE
`Initialize-TssSdkClient` Notes Need To Be Updated

### ISSUE THREAD

**Issue by aotongarcia** [thycotic-ps/thycotic.secretserver#371]
### Summarize Functionality

The `Notes` section for [Initialize-TSSSdkClient](https://thycotic-ps.github.io/thycotic.secretserver/commands/authentication/Initialize-TssSdkClient.html#initialize-tsssdkclient) points to a dead URL. It should be updated to https://docs.delinea.com/online-help/secret-server/api-scripting/sdk-cli/index.htm#Task1ConfiguringSecretServer

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

N/A

**Comment by tylerezimmerman** [comment]
Resolved in 0.61.4
