### ISSUE TITLE
ClientSDK directory not packaged with 0.61.4 deployment

### ISSUE THREAD

**Issue by skywayskase** [thycotic-ps/thycotic.secretserver#378]
### Verified issue does not already exist?

Yes

### What error did you receive

PSMessageDetails      :
Exception             : System.Exception: Exception calling "Start" with "0" argument(s): "An error occurred trying to
                        start process 'C:\Program
                        Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4\bin\ClientSdk\tss.exe' with working
                        directory 'C:\Users\\{removed}\Documents\GitHub\User-Management'. The system cannot find the
                        file specified."
TargetObject          :
CategoryInfo          : NotSpecified: (:) [ErrorHandling.ps1], Exception
FullyQualifiedErrorId : ResultError,ErrorHandling.ps1
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock><Process>, C:\Program
                        Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4\parts\ErrorHandling.ps1: line 10
                        at Test-TssSdkClient<Process>, C:\Program Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4
                        \functions\authentication\Test-TssSdkClient.ps1: line 94
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Please run the command using -Verbose

VERBOSE: Command invocation: Test-TssSdkClient -SecretServer:https://{removed}.secretservercloud.com -ConfigPath:C:\Users\{removed}\TSSConfig -Verbose:True
VERBOSE: arguments for tss status: status --key-directory C:\Users\\{removed}\TSSConfig --config-directory C:\Users\\{removed}\TSSConfig
WARNING: Issue checking status of SDK Client (tss) for [https://{removed}.secretservercloud.com]
Test-TssSdkClient: Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:\Program Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4\bin\ClientSdk\tss.exe' with working directory 'C:\Users\\{removed}\Documents\GitHub\User-Management'. The system cannot find the file specified."
ErrorHandling.ps1: C:\Program Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4\functions\authentication\Test-TssSdkClient.ps1:94
Line |
  94 |              . $ErrorHandling $err
     |              ~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Start" with "0" argument(s): "An error occurred trying to start process 'C:\Program
     | Files\PowerShell\Modules\Thycotic.SecretServer\0.61.4\bin\ClientSdk\tss.exe' with working directory
     | 'C:\Users\\{removed}\Documents\GitHub\User-Management'. The system cannot find the file specified."

### Provide a test case or steps to reproduce

I've installed 0.61.4 on a few different computers and confirmed that ```.\Thycotic.SecretServer.\0.61.4\bit\ClientSDK``` doesn't exist. I even went [Powershell Gallery](https://www.powershellgallery.com/packages/Thycotic.SecretServer/0.61.4) and checked the file list for the most recent version and found that no files in that directory are listed.

### Expected behavior

I'd expect the ```.\bin\ClientSDK``` directory to exist so that I can use the client sdk. I think the module may need to be redeployed.

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

PowerShell Core (pwsh)

### PowerShell Host Version

7.3.7

**Comment by skywayskase** [comment]
This is a pretty major issue. I did a diff between label 0.61.3 and 0.61.4 and while many of the files in that directory have been updated, I didn't see any reason why they wouldn't be packaged with the newest deployment.

**Comment by tylerezimmerman** [comment]
@skywayskase this should be resolved in the 0.61.5 release published to the Powershell Gallery moments ago. Can you verify at your convince?

**Comment by skywayskase** [comment]
@tylerezimmerman I can confirm that everything looks good now. Thanks for getting this resolved!
