### ISSUE TITLE
New Error with Powershell Get-TssSecret

### ISSUE THREAD

**Issue by jmackxiii** [thycotic-ps/thycotic.secretserver#385]
### Verified issue does not already exist?

Yes

### What error did you receive

Starting Saturday we are unable to use a script we have been using forever now. We have not made any changes to the script or environment and troubleshooting the script.. the offending part is "Get-TssSecret -TssSession $session -Id 111447".. when trying this command we get this long error about the module function.... Cannot convert value "@{id=111447; name=AH-svcVMSnapReport; secretTemplateId=6191; folderId=5651; active=True; items=System.Object[]; launcherConnectAsSecretId=-1; checkOutMinutesRemaining=0; checkedOut=False; 
checkOutUserDisplayName=; checkOutUserId=-1; isRestricted=False; isOutOfSync=False; outOfSyncReason=; autoChangeEnabled=True; autoChangeNextPassword=; requiresApprovalForAccess=False; requiresComment=False; 
checkOutEnabled=False; checkOutIntervalMinutes=-1; checkOutChangePasswordEnabled=False; accessRequestWorkflowMapId=-1; proxyEnabled=True; sessionRecordingEnabled=False; restrictSshCommands=False; jumpboxRouteId=; 
allowOwnersUnrestrictedSshCommands=False; isDoubleLock=False; doubleLockId=-1; enableInheritPermissions=True; passwordTypeWebScriptId=-1; siteId=46; enableInheritSecretPolicy=True; secretPolicyId=158; 
lastHeartBeatStatus=Success; lastHeartBeatCheck=2024-01-22T08:55:54.657; failedPasswordChangeAttempts=0; lastPasswordChangeAttempt=0001-01-01T00:00:00; secretTemplateName=AH-AD_Service_Accounts; 
responseCodes=System.Object[]; webLauncherRequiresIncognitoMode=False; hsmKeyIdentifier=}" to type "Thycotic.PowerShell.Secrets.Secret". Error: "Cannot convert the "@{id=111447; name=AH-svcVMSnapReport; 
secretTemplateId=6191; folderId=5651; active=True; items=System.Object[]; launcherConnectAsSecretId=-1; checkOutMinutesRemaining=0; checkedOut=False; checkOutUserDisplayName=; checkOutUserId=-1; isRestricted=False; 
isOutOfSync=False; outOfSyncReason=; autoChangeEnabled=True; autoChangeNextPassword=; requiresApprovalForAccess=False; requiresComment=False; checkOutEnabled=False; checkOutIntervalMinutes=-1; 
checkOutChangePasswordEnabled=False; accessRequestWorkflowMapId=-1; proxyEnabled=True; sessionRecordingEnabled=False; restrictSshCommands=False; jumpboxRouteId=; allowOwnersUnrestrictedSshCommands=False; 
isDoubleLock=False; doubleLockId=-1; enableInheritPermissions=True; passwordTypeWebScriptId=-1; siteId=46; enableInheritSecretPolicy=True; secretPolicyId=158; lastHeartBeatStatus=Success; 
lastHeartBeatCheck=2024-01-22T08:55:54.657; failedPasswordChangeAttempts=0; lastPasswordChangeAttempt=0001-01-01T00:00:00; secretTemplateName=AH-AD_Service_Accounts; responseCodes=System.Object[]; 
webLauncherRequiresIncognitoMode=False; hsmKeyIdentifier=}" value of type "System.Management.Automation.PSCustomObject" to type "Thycotic.PowerShell.Secrets.Secret"."
At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.61.0\functions\secrets\Get-TssSecret.ps1:240 char:25
+ ...                     [Thycotic.PowerShell.Secrets.Secret]$restResponse
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException

### Please run the command using -Verbose

PS C:\Users\11jmack> Get-TssSecret -TssSession $session -Id 111447 -Verbose
VERBOSE: Command invocation: Get-TssSecret -TssSession:TssSessionObject -Id:System.Int32[] -Verbose:True
VERBOSE: Performing the operation GET  https://oct.secretservercloud.com/api/v1/secrets/111447 with:	

Cannot convert value "@{id=111447; name=AH-svcVMSnapReport; secretTemplateId=6191; folderId=5651; active=True; items=System.Object[]; launcherConnectAsSecretId=-1; checkOutMinutesRemaining=0; checkedOut=False; 
checkOutUserDisplayName=; checkOutUserId=-1; isRestricted=False; isOutOfSync=False; outOfSyncReason=; autoChangeEnabled=True; autoChangeNextPassword=; requiresApprovalForAccess=False; requiresComment=False; 
checkOutEnabled=False; checkOutIntervalMinutes=-1; checkOutChangePasswordEnabled=False; accessRequestWorkflowMapId=-1; proxyEnabled=True; sessionRecordingEnabled=False; restrictSshCommands=False; jumpboxRouteId=; 
allowOwnersUnrestrictedSshCommands=False; isDoubleLock=False; doubleLockId=-1; enableInheritPermissions=True; passwordTypeWebScriptId=-1; siteId=46; enableInheritSecretPolicy=True; secretPolicyId=158; 
lastHeartBeatStatus=Success; lastHeartBeatCheck=2024-01-22T08:55:54.657; failedPasswordChangeAttempts=0; lastPasswordChangeAttempt=0001-01-01T00:00:00; secretTemplateName=AH-AD_Service_Accounts; 
responseCodes=System.Object[]; webLauncherRequiresIncognitoMode=False; hsmKeyIdentifier=}" to type "Thycotic.PowerShell.Secrets.Secret". Error: "Cannot convert the "@{id=111447; name=AH-svcVMSnapReport; 
secretTemplateId=6191; folderId=5651; active=True; items=System.Object[]; launcherConnectAsSecretId=-1; checkOutMinutesRemaining=0; checkedOut=False; checkOutUserDisplayName=; checkOutUserId=-1; isRestricted=False; 
isOutOfSync=False; outOfSyncReason=; autoChangeEnabled=True; autoChangeNextPassword=; requiresApprovalForAccess=False; requiresComment=False; checkOutEnabled=False; checkOutIntervalMinutes=-1; 
checkOutChangePasswordEnabled=False; accessRequestWorkflowMapId=-1; proxyEnabled=True; sessionRecordingEnabled=False; restrictSshCommands=False; jumpboxRouteId=; allowOwnersUnrestrictedSshCommands=False; 
isDoubleLock=False; doubleLockId=-1; enableInheritPermissions=True; passwordTypeWebScriptId=-1; siteId=46; enableInheritSecretPolicy=True; secretPolicyId=158; lastHeartBeatStatus=Success; 
lastHeartBeatCheck=2024-01-22T08:55:54.657; failedPasswordChangeAttempts=0; lastPasswordChangeAttempt=0001-01-01T00:00:00; secretTemplateName=AH-AD_Service_Accounts; responseCodes=System.Object[]; 
webLauncherRequiresIncognitoMode=False; hsmKeyIdentifier=}" value of type "System.Management.Automation.PSCustomObject" to type "Thycotic.PowerShell.Secrets.Secret"."
At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.61.0\functions\secrets\Get-TssSecret.ps1:240 char:25
+ ...                     [Thycotic.PowerShell.Secrets.Secret]$restResponse
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException

### Provide a test case or steps to reproduce

$secret = Get-TssSecret -TssSession $session -Id 111447 

### Expected behavior

This should load the expected secret details but will error out when running. 

### What Edition of Secret Server?

Cloud Subscription

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                           
----                           -----                                                                                                                                                                                           
PSVersion                      5.1.14393.6343                                                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                         
BuildVersion                   10.0.14393.6343                                                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                             
SerializationVersion           1.1.0.1

**Comment by jmackxiii** [comment]
Adding more details.. trying search-tsssecret yields similar results..

PS C:\Users\11jmack> Search-TssSecret -TssSession $session -SecretName 'AH-svcVMSnapReport' -Verbose
VERBOSE: Command invocation: Search-TssSecret -TssSession:TssSessionObject -SearchText:AH-svcVMSnapReport -Verbose:True
VERBOSE: Filters: filter.searchText=AH-svcVMSnapReport
VERBOSE: Performing the operation GET https://oct.secretservercloud.com/api/v1/secrets?sortBy[0].direction=asc&sortBy[0].name=Name&take=2147483647&filter.includeRestricted=true&filter.searchText=AH-svcVMSnapReport
Cannot convert value "@{id=111447; name=AH-svcVMSnapReport; secretTemplateId=6191; secretTemplateName=AH-AD_Service_Accounts; folderId=5651; folderPath=\AH\IT\Management Accounts\Service Accounts\Daily Change; siteId=46; 
active=True; checkedOut=False; isRestricted=False; isOutOfSync=False; outOfSyncReason=; lastHeartBeatStatus=Success; lastPasswordChangeAttempt=0001-01-01T00:00:00; responseCodes=; lastAccessed=2024-01-22T14:45:10.463; 
extendedFields=; checkOutEnabled=False; autoChangeEnabled=True; doubleLockEnabled=False; requiresApproval=False; requiresComment=False; inheritsPermissions=True; hidePassword=False; createDate=2022-08-08T17:46:13.157; 
daysUntilExpiration=364; hasLauncher=True; checkOutUserId=-1; checkOutUserName=}" to type "Thycotic.PowerShell.Secrets.Summary". Error: "Cannot convert the "@{id=111447; name=AH-svcVMSnapReport; secretTemplateId=6191; 
secretTemplateName=AH-AD_Service_Accounts; folderId=5651; folderPath=\AH\IT\Management Accounts\Service Accounts\Daily Change; siteId=46; active=True; checkedOut=False; isRestricted=False; isOutOfSync=False; 
outOfSyncReason=; lastHeartBeatStatus=Success; lastPasswordChangeAttempt=0001-01-01T00:00:00; responseCodes=; lastAccessed=2024-01-22T14:45:10.463; extendedFields=; checkOutEnabled=False; autoChangeEnabled=True; 
doubleLockEnabled=False; requiresApproval=False; requiresComment=False; inheritsPermissions=True; hidePassword=False; createDate=2022-08-08T17:46:13.157; daysUntilExpiration=364; hasLauncher=True; checkOutUserId=-1; 
checkOutUserName=}" value of type "System.Management.Automation.PSCustomObject" to type "Thycotic.PowerShell.Secrets.Summary"."
At C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.61.0\functions\secrets\Search-TssSecret.ps1:274 char:17
+ ...             [Thycotic.PowerShell.Secrets.Summary[]]$restResponse.reco ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastConstructorException

**Comment by jagger** [comment]
Possibly connected to #384

**Comment by jmackxiii** [comment]
Found that "fix" earlier.. but I have applied that modification but it still returns the same error, however Get-TssSecretField works.

**Comment by apsyka93** [comment]
Same error, since the last update from secret server cloud on jan 19th.
https://docs.delinea.com/online-help/secret-server-changelog/secret-server-change-log.htm

**Comment by jgeron-suhsd** [comment]
I suddenly started getting this same error as well.

**Comment by jagger** [comment]
Resolved in latest release
