### ISSUE TITLE
New-TssSession requires that -SecretServer parameter URL ends with slash

### ISSUE THREAD

**Issue by peetrike** [thycotic-ps/thycotic.secretserver#72]
**Describe the bug**
New-TssSession constructs wrong API URL, when provided SecretServer URL doesn't end with slash (`/`).  After that, all commands using created session will fail with error message:
```
  404 - File or directory not found.
  The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
```

**To Reproduce**
1. PowerShell script:

```powershell
$session = New-TssSession -SecretServer https://myserver/secretserver -Credential $credential
$session.ApiUrl
```

1. Error/issue observed:

```powershell
Search-TssFolder -TssSession $session
```

**Expected behavior**
list of folders

**Actual result**
```output
WARNING: Issue on search request
Exception: C:\Program Files\WindowsPowerShell\Modules\thycotic.secretserver\0.29.0\parts\ErrorHandling.ps1:9
Line |
   9 |          throw $errDetailMsg
     |          ~~~~~~~~~~~~~~~~~~~
     |     404 - File or directory not found.      Server Error      404 - File or directory not found.   The
     | resource you are looking for might have been removed, had its name changed, or is temporarily
     | unavailable.
```

**Screenshots**

**Environment (please complete the following information):**
PowerShell 5.1 and 7.1.1 on Windows

***Host information:***

[x] Powershell.exe
[x] pwsh.exe
[ ] PowerShell ISE
[ ] VS Code (Insiders/Stable)

**Comment by wsmelton** [comment]
Identified fix, but will need to adjust my test environment I use to run the Pester tests.

A quick band-aid if you want will be to adjust the following line:

https://github.com/thycotic-ps/thycotic.secretserver/blob/76af2d00c59e6e3fbed0a4d4cd1d55e3b46556e2/src/functions/New-Session.ps1#L72

Adjust that to this:

```powershell
$outputTssSession.ApiUrl = $outputTssSession.SecretServer, $outputTssSession.ApiVersion -join '/'
```

**Comment by peetrike** [comment]
it would be better to do something like this:
```powershell
 $outputTssSession.ApiUrl = if ($SecretServer -match '/$') {
  $outputTssSession.SecretServer + $outputTssSession.ApiVersion
} else {
  $outputTssSession.SecretServer, $outputTssSession.ApiVersion -join '/'
}
```

**Comment by wsmelton** [comment]
The join covers all scenarios.

**Comment by peetrike** [comment]
> The join covers all scenarios. I'll update the Pester test to catch to ensure it does not regress.

in PowerShell 5.1, join creates path with double '/' if $secretServer ends with '/'.  Usually it works, but looks not so good.

**Comment by peetrike** [comment]
you can always remove last '/' if it exists:
```powershell
$outputTssSession.ApiUrl = ($outputTssSession.SecretServer -replace '/$', '') + $outputTssSession.ApiVersion
```

**Comment by peetrike** [comment]
and something similar could be done here:
https://github.com/thycotic-ps/thycotic.secretserver/blob/76af2d00c59e6e3fbed0a4d4cd1d55e3b46556e2/src/functions/New-Session.ps1#L82

**Comment by wsmelton** [comment]
There is no change required on line 82 in this case because the SecretServer value is being processed in the beginning block.

**Comment by peetrike** [comment]
you use there original input parameter value, not the value from class.

**Comment by wsmelton** [comment]
Ah, sure am. I'll get that fixed as well.

**Comment by wsmelton** [comment]
Testing this the use of `TrimEnd('/')` is not an option because of how the input is accepted (URI does not have Trim methods) and adding it to when the value is set on the SecretServer property does nothing. The later I thought would have since that is a string type but determined easier path is just not use `-join` at all.

Adjusting this I am no longer able to replicate the issue and that seems to fix it.

Tests should already be catching an improper value being created for the ApiUrl (test will fail if 404 is returned). Will test current build and then with the fix to make sure though. Release with this fix should be out by Monday.

**Comment by wsmelton** [comment]
7eeb8d8
